### ISSUE TITLE
Kafka loopback: Test using messages from dojot to devices

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1270]
Objective: create MQTT Client to retrieve messages from Kafka and send them to devices through VerneMQ. 

Subtasks

- [x] Expose Kafka key and partition in Kafka Messenger publishing function
- [x] Expose kafka message value, size, key, topic, offset, partition, timestamp
- [x] Disconnect function in Kafka Messenger
- [x] Create Kafka/Data-Broker Plugin for Vernemq
- [x] Create mqtt-bridge

**Comment by rascaraficci** [comment]
Done!
