### ISSUE TITLE
Development Integrated Test

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1271]
- [x] Code to force devices to reconnect every 30 minutes (Muhamed)
- [x] Code to renew the Broker certificate twice in 72h (Mariane)
- [x] Code to renew 1% of devices in 72h (Eduardo)
- [x] Code to revoke 1% of devices in 72h (Eduardo)

100k tests with:
- [x] Renew
- [x] Revoke
- [x] Renew and revoke
- [x] Disconnect plugin

**Comment by mprevide** [comment]
It's important to differentiate revoke and expiration in the broker. I will do some tests yet.
