### ISSUE TITLE
Defining repository structure to hold new MQTT IoT- Agent

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1306]

**Comment by raulnegreiros** [comment]
Write a document that covers the following aspects:

- [x] repository structure to hold the new MQTT IoTAgenT
- [x] repository structure to hold the dojot as a whole in a monorepo style
- [x] list the continuous integration tools
- [ ] describe the workflow to create a baseline
- [ ] describe the workflow to create a hotfix
