### ISSUE TITLE
IotAgent VerneMQ MQTT integration with dojot 

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1314]
- [x] Adequate the new K2V Bridge implementation to Dojot patterns
- [x] Adequate the V2K Bridge implementation to Dojot patterns
- [x] Test using the new K2V Bridge implementation
- [x] Test using V2K Bridge
- [x] Adequate Ansible to run all Dojot's services
