### ISSUE TITLE
Epic: x.509 Identities for dojot

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1402]
- [ ] 2.1 REST API - Proposal
    - Register Trusted CA Certificate
    - Delete Trusted CA Certificate
    - Update Trusted CA Certificate
    - List Trusted CA Certificates
    - Get Trusted CA Certificate
    - Register x.509 Certificate Issued by an External CA
    - &#x2713; Create x.509 Certificate from CSR
    - &#x2713; Delete x.509 certificate
    - &#x2713; List x.509 Certificates
    - &#x2713; Get x.509 Certificate
    - &#x2713; Change the Ownership of a Specified x.509 Certificate
- [ ] 2.2 Inter services communication - Proposal
- [ ] 2.3 Big Picture - Proposal

**Comment by thiagodpf** [comment]
The code was merged through this PR:
https://github.com/dojot/dojot/pull/1469

**Comment by thiagodpf** [comment]
This ticket will be closed and we will divide the missing activities into separate tickets.
