### ISSUE TITLE
Epic 100K - System tuning

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1493]
**System Tuning**
**Kafka**
- [x] Log retention and size
- [x] Isolate the pod
- [x] Add volume

**K2V**
- [x] Change number of instances

**V2K**
- [x] Backpressure max queue length
- [x] Activate compression
- [x] Queue buffering max time
- [x] Change number of instances

**VerneMQ**
- [x] Tune max_*_messages parameters
- [x] Erlang internode communication buffer size
- [x] Async threads number and size
- [x] Change number of instances
- [x] Test with disconnect plugin

**k8s**
- [x] Upgrade k8s version to 1.17
- [x] Enable service topology on k8s 1.17
- [x] Apply service topology in the 100k environment

**HAProxy**
- [x] Configure HAProxy as load balancer

**Locust**
- [x] Test with Revoke
- [x] Test with Renew
- [x] Test with Renew and Revoke

**Stack Prometheus/Grafana**
- [x] Update Prometheus
- [x] Update Grafana
- [x] Update Node Exporter
- [x] Persistent storage

**Fixes**
**Stack Prometheus/Grafana**
- [x] Fix metrics for k8s 1.17

**VerneMQ**
- [x] Add tini to prevent zombie processes

**V2K**
- [x] Update to SDK lib
- [x] Update MQTT library

**K2V**
- [x] Update to SDK lib
- [x] Update MQTT library
- [x] Fix process hanging when an already made connection with VerneMQ is broken (temporary fix, should investigate later)

**New EJBCA**
- [x] Volume for EJBCA data (neither PostgreSQL nor MongoDB related)
- [x] Test scalability
- [x] Test performance when in a separate node

**Comment by bizetti** [comment]
It has finished to alpha4 version.
