### ISSUE TITLE
Deployment - Including VerneMQ and new components

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1495]
- [X] PR with changes do k8s 1.17
  - [X] PR to enable topology service for VeneMQ
  - [X] PR to use VerneMQ pods on the same host that received the request.
  - [X] Analyze whether any further changes are required for the 100k
  - [x] Change some deployments to statefulset
  - [x] Map volumes on some components

**Comment by rascaraficci** [comment]
done!
