### ISSUE TITLE
Documentation - Review component/service documentation for dojot version 0.5.0

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1584]
A ideia aqui é revisar e atualizar o que for necessário nas documentações.

Nota: As alteração feitas devem ser replicadas para o branch release/v0.5.0, release/v0.4.3 (caso faça sentido)  e development

- [**Auth**](https://github.com/dojot/auth)
  - [x] transferir para readme, readthedocs  (https://dojotdocs.readthedocs.io/projects/auth/en/latest/, https://github.com/dojot/auth/blob/release/v0.5.0/docs/index.rst) @eduardogmisiuk 
  - [x] API(https://dojot.github.io/auth/apiary_latest.html, https://github.com/dojot/auth/blob/release/v0.5.0/docs/apiary.apib) @mprevide
  - [x] readme (https://github.com/dojot/auth/blob/release/v0.5.0/README.md) @eduardogmisiuk 
  - [x] #1689 @mprevide
  - [x] dojot/auth#112 @eduardogmisiuk 
  - [x] dojot/auth#113 @eduardogmisiuk 

- [**History**](https://github.com/dojot/history)
  - [x] dojot/dojot#1457 @mprevide 
  - [x] api (https://dojot.github.io/history/apiary_latest.html, https://github.com/dojot/history/blob/release/v0.5.0/docs/history.apib) @mprevide
  - [x] readme (https://github.com/dojot/history/blob/release/v0.5.0/README.md) @thiagof

- [**Device Manager**](https://github.com/dojot/device-manager/) @eduardogmisiuk 
  - [x]  transferir para readme  (https://github.com/dojot/device-manager/blob/development/docs/index.rst, https://github.com/dojot/device-manager/blob/release/v0.5.0/docs/index.rst)
  - [x] api (https://dojot.github.io/device-manager/apiary_latest.html, https://github.com/dojot/device-manager/blob/release/v0.5.0/docs/apiary.apib)
  - [x] readme (https://github.com/dojot/device-manager/blob/release/v0.5.0/README.md)
  - [x] https://github.com/dojot/device-manager/pull/160
  - [x] https://github.com/dojot/device-manager/pull/163

- [**Image Manager**](https://github.com/dojot/image-manager) @eduardogmisiuk 
  - [x] api (https://dojot.github.io/image-manager/apiary_latest.html, https://github.com/dojot/image-manager/blob/release/v0.5.0/docs/api.apib)
  - [x] readme (https://github.com/dojot/image-manager/blob/release/v0.5.0/README.md)
  - [x] https://github.com/dojot/image-manager/pull/45
  - [x] https://github.com/dojot/image-manager/pull/46
  - [x] https://github.com/dojot/image-manager/pull/47

- [**Flowbroker**](https://github.com/dojot/flowbroker)  @mprevide 
  - [x] api (https://dojot.github.io/flowbroker/apiary_latest.html,  https://github.com/dojot/flowbroker/blob/release/v0.5.0/docs/api.apib) @jonaphael
  - [x] readme (https://github.com/dojot/flowbroker/blob/release/v0.5.0/README.md)
  - [x] Remover o que não faz mais sentido da pasta: https://github.com/dojot/flowbroker/tree/v0.5.0/docs
  - [x] lib:  https://github.com/dojot/flowbroker/tree/release/v0.5.0/lib

- [**Data Broker**](https://github.com/dojot/data-broker) @eduardogmisiuk
  - [x] readme (https://github.com/dojot/data-broker/blob/release/v0.5.0/README.md)
  - [x] https://github.com/dojot/data-broker/pull/94
  - [x] api (https://dojot.github.io/data-broker/apiary_latest.html,  https://github.com/dojot/data-broker/blob/release/v0.5.0/docs/data-broker.apib)
  - [x] https://github.com/dojot/data-broker/pull/96
  - [x] https://github.com/dojot/data-broker/pull/97

- IotAgent Mosca
  - [x] falar q o timestamp pode ser passado como payload e qual é aceito (unixtime em ms, sec e iso? testar como o persister/history lida com os 3 casos) @eduardogmisiuk 
  - [x] dojot/iotagent-mosca#108  @eduardogmisiuk 
  - [x] dojot/iotagent-mosca#109  @eduardogmisiuk 

Libraries:

- [**Microservice SDK**](https://github.com/dojot/dojot-microservice-sdk-js) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot-microservice-sdk-js/blob/development/README.md)
  - [x] https://github.com/dojot/dojot-microservice-sdk-js/pull/9

**[dojot/dojot](https://github.com/dojot/dojot)**

- [**connector/kafka2ftp**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/kafka2ftp)
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/connector/kafka2ftp/README.md) @mprevide

- [**connector/mqtt/vernemq**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq) @thiagodpf 
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/connector/mqtt/vernemq/README.md)
  
- [**connector/mqtt/vernemq/broker**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/broker) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/connector/mqtt/vernemq/broker/README.md)
  - [x] https://github.com/dojot/dojot/pull/1698
  - [x] https://github.com/dojot/dojot/pull/1709

- [**connector/mqtt/vernemq/broker/src/dojot_acl_plugin**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/broker/src/dojot_acl_plugin) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/broker/src/dojot_acl_plugin/readme.md)
  - [x] https://github.com/dojot/dojot/pull/1698
  - [x] https://github.com/dojot/dojot/pull/1709

- [**connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/broker/src/dojot_disconnect_plugin/readme.md)
  - [x] https://github.com/dojot/dojot/pull/1698
  - [x] https://github.com/dojot/dojot/pull/1709

- [**connector/mqtt/vernemq/k2v-bridge**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/k2v-bridge) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/connector/mqtt/vernemq/k2v-bridge/README.md)
  - [x] https://github.com/dojot/dojot/pull/1695
  - [x] https://github.com/dojot/dojot/pull/1707

- [**connector/mqtt/vernemq/v2k-bridge**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/vernemq/v2k-bridge) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/connector/mqtt/vernemq/v2k-bridge/README.md)
  - [x] https://github.com/dojot/dojot/pull/1696
  - [x] https://github.com/dojot/dojot/pull/1708
  - [x] https://github.com/dojot/dojot/pull/1710

- [**connector/mqtt/locust**](https://github.com/dojot/dojot/tree/release/v0.5.0/connector/mqtt/locust) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/connector/mqtt/locust/README.md)
  - [x] https://github.com/dojot/dojot/pull/1742
  - [x] https://github.com/dojot/dojot/pull/1758

- [**subscription-engine/kafka-ws**](https://github.com/dojot/dojot/tree/release/v0.5.0/subscription-engine/kafka-ws)
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/subscription-engine/kafka-ws/README.md)
  - [x] api (https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_release-v0.5.0.html, https://github.com/dojot/dojot/blob/release/v0.5.0/subscription-engine/kafka-ws/docs/apiary.apib) @eduardogmisiuk 
  - [x] https://github.com/dojot/dojot/pull/1748
  - [x] https://github.com/dojot/dojot/pull/1757
  - [x] https://github.com/dojot/dojot/pull/1759

- [**tools/kafka/loopback**](https://github.com/dojot/dojot/tree/release/v0.5.0/tools/kafka/loopback) @eduardogmisiuk 
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/tools/kafka/loopback/README.md)
  - [x] https://github.com/dojot/dojot/pull/1699
  - [x] https://github.com/dojot/dojot/pull/1706

- [**x509-identity-mgmt**](https://github.com/dojot/dojot/tree/release/v0.5.0/x509-identity-mgmt)
  - [x] readme (https://github.com/dojot/dojot/blob/release/v0.5.0/x509-identity-mgmt/README.md)
  - [x] api (https://dojot.github.io/dojot/x509-identity-mgmt/apiary_release-v0.5.0.html, https://github.com/dojot/dojot/blob/release/v0.5.0/x509-identity-mgmt/js/apidocs/api-description.apib)

**Comment by mprevide** [comment]
- Auth (https://github.com/dojot/auth)
  - [ ] readthedocs (https://dojotdocs.readthedocs.io/projects/auth/en/latest/, https://github.com/dojot/auth/blob/release/v0.5.0-alpha/docs/index.rst)
  - [ ] api (https://dojot.github.io/auth/apiary_latest.html, https://github.com/dojot/auth/blob/release/v0.5.0-alpha/docs/apiary.apib)
  - [ ] readme (https://github.com/dojot/auth/blob/release/v0.5.0-alpha/README.md)
- History (https://github.com/dojot/history)
  - [ ] api (https://dojot.github.io/history/apiary_latest.html, https://github.com/dojot/history/blob/release/v0.5.0-alpha/docs/history.apib)
  - [ ] readme (https://github.com/dojot/history/blob/release/v0.5.0-alpha/README.md)

**Comment by bizetti** [comment]
Released with version 0.5.0.
