### ISSUE TITLE
Backlog for pre-release v0.5.0-alpha.4

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1679]
Read The docs  (Work in progress)
--------------------------

https://dojotdocs.readthedocs.io/en/release-v0.5.0/
https://dojotdocs.readthedocs.io/pt_BR/release-v0.5.0/

### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/history/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/device-manager/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/image-manager/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/flowbroker/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/data-broker/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/data-manager/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/cron/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.5.0-alpha.4.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.5.0-alpha.4.html

dojot/history
-------------

 - [x] dojot/history#80, linked issues dojot/dojot#1457: doc: More detail on api documentation [0.5]
 - [ ] dojot/history#71: fix: add index and fix event create 
 - [ ] dojot/history#74: chore: fix pip version - travis

dojot/iotagent-mosca
--------------------

 - [ ] dojot/iotagent-mosca#102, linked issues dojot/dojot#1605 dojot/dojot#1201 dojot/dojot#1235:  chore: update to use the new X.509 Identity Management 

dojot/gui
---------

 - [ ] dojot/gui#634: Revert "fix: date correction on the device chart v0.5.0"
 - [x] dojot/gui#630, linked issues dojot/dojot#1508: fix: Error showing Tenant
 - [x] dojot/gui#626, linked issues dojot/dojot#1464: fix: date correction on the device chart v0.5.0
 - [x] dojot/gui#625, linked issues dojot/dojot#1165: Validation for importing firmware v0.5.0
 - [x] dojot/gui#624, linked issues dojot/dojot#1212: correcting the flow date v0.5.0

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#281, linked issues dojot/dojot#1645 dojot/dojot#1650: fix: some undefined  variables in http node [v0.5.0]
 - [ ] dojot/flowbroker#256: chore: upgrade libs examples [release/v0.5.0-alpha]
 - [x] dojot/flowbroker#276, linked issues dojot/dojot#1156: Change portuguese translation
 - [x] dojot/flowbroker#275, linked issues dojot/dojot#1298: Remove mandatory field on GET message (**Rejected**)
 - [x] dojot/flowbroker#274, linked issues dojot/dojot#1377: Add parameter to del remote node (to 0.5.0)
 - [ ] dojot/flowbroker#262, linked issues dojot/dojot#1565: feat: Changed to process messages in parallel  [release/v0.5.0]

dojot/backstage
---------------

 - [x] dojot/backstage#53, linked issues dojot/dojot#1672: Ordering values for the dashboard
 - [ ] dojot/backstage#51, linked issues dojot/dojot#1567:  feat: Change to handle dates in seconds, milliseconds and microseconds
 - [ ] dojot/backstage#49, linked issues dojot/dojot#1567: Release/v0.5.0 alpha

dojot/dojot
-----------

 - [ ] dojot/dojot#1644, linked issues dojot/dojot#1584: [Release v0.5.0] Update IoT Agent MqTT docs
 - [ ] dojot/dojot#1581: [release] - crl download fix
 - [x] dojot/dojot#1665, linked issues dojot/dojot#1637: [release] Add bool operator
 - [ ] dojot/dojot#1641, linked issues dojot/dojot#1626: [release] [locust] Add Locust Exporter
 - [ ] dojot/dojot#1664: [release] Fix v2k timestamp
 - [ ] dojot/dojot#1638: [release] [locust] Correct --remove behaviour
 - [x] dojot/dojot#1657, linked issues dojot/dojot#1651: [release] Fix parameter name parsing
 - [x] dojot/dojot#1655, linked issues dojot/dojot#1621: [release] Enhance fields documentation
 - [x] dojot/dojot#1646, linked issues dojot/dojot#1635: [release] Fix number parsing
 - [ ] dojot/dojot#1643: Bringing CertTools from "development" to "feature 0.5.0"
 - [ ] dojot/dojot#1624: [release] Fix Locust Docker files
 - [ ] dojot/dojot#1616: Improved documentation x509-identity-mnmt
 - [ ] dojot/dojot#1597: [feature] Add new Kafka WS example that works with Dojot environment
 - [ ] dojot/dojot#1609: chore: remove sdk from dojot/dojot and add to a new repository [release/v0.5.0]
 - [ ] dojot/dojot#1599: Add environment variable to enable requesting certificates from client

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#60: create v0.5.0-alpha.4
 - [ ] dojot/ansible-dojot#61: Correct identation
 - [ ] dojot/ansible-dojot#59, linked issues dojot/dojot#1600: nginx version and update cache
 - [x] dojot/ansible-dojot#55, linked issues dojot/dojot#1604: Allow choosing VerneMQ, Mosca or LWM2M on dojot deploy
 - [ ] dojot/ansible-dojot#52, linked issues dojot/dojot#1626: [feature] Add Locust Exporter
 - [ ] dojot/ansible-dojot#57, linked issues dojot/dojot#1600 dojot/dojot#1591: Replacement of HAProxy by NGINX
 - [ ] dojot/ansible-dojot#56, linked issues dojot/dojot#1615 dojot/dojot#1603: GUI V2 deployment
 - [ ] dojot/ansible-dojot#51: [enhance] Parameterize Node Affinity
 - [ ] dojot/ansible-dojot#49: Add TLS configurations to Kafka WS and Kong

gui-v2
--------
#1379

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.5.0-alpha.4
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.5.0-alpha.4
----
