### ISSUE TITLE
Test: Test activities for baseline alfa 4 (0.5.0)

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1691]
- [X] Basic sanity test

- [X] Websocket execution test 

- [ ] 100K execution test (without dojot)
  - [ ] Performance test
  - [ ] Long-term test

- [ ] 100K execution teste (with dojot)

- [x] Dashboard execution test

- [x] EJBCA execution test (X.509)
----
- [X] Functionalities execution test using **APIs** (P1)

  - [X] Sanity Test  
  - [X] Template
  - [X] Devices
  - [X] Update de firmware
  - [X] Flows
  - [ ] Remote nodes (**blocked**) (#1548)
  - [X] Notifications (P1)
  - [X] Users 
  - [X] User profiles 
  - [ ] Import / Export (**blocked**)(#1480)
  - [X] Scheduling (cron)
  - [X] Tests with another tenant
----
- [ ] Funcionalities execution test using **GUI**

  - [x] Sanity Test (Franciele)
  - [x] Template (Franciele)
  - [x] Devices (Franciele)
  - [ ] Certificates generation  (**blocked**)(#1441 )
  - [x] Secure publishing (certificates generated by certreq)
       - [x] Verne (Franciele)
       - [x] Mosca 
  - [x] Insecure publishing
       - [x] Verne 
       - [x] Mosca 
  - [x] Map view (Franciele)
  - [X] Update de firmware (P1)
  - [ ] Update de firmware (P2,P3)
  - [x] Flows
       Nodes:
       - [x] Device Event in
       - [x] Device template event in
       - [x] Multi device out
       - [x] Multi actuate
       - [x] HTTP request
          - [x] POST
          - [x] GET (#1298)
          - [x] JSON
       - [x] FTP request
       - [x] Publish in FTP topic
       - [x] Notification
       - [x] Change
       - [x] Switch
       - [x] Template
       - [x] Cron
          - [x] Event request
          - [x] HTTP request
       - [x] Cron batch
          - [x] broker
          - [x] HTTP
       - [x] Geofence
       - [ ] Get Context
       - [x] Merge data
       - [x] Cumulative sum
       - [x] Deprecated nodes
          - [x] Device in
          - [x] Device template in
          - [x] Device out
          - [x] Actuate
  - [ ] Remote nodes (**blocked**) (#1548)
  - [x] Notifications
  - [x] Users (Franciele)
  - [x] User profiles (Franciele)
  - [ ] Import / Export  (**blocked**)(#1480)
----
  - [x] Tests with another tenant (**Franciele**)
       - [ ] Import / Export  (**blocked**)(#1480)
       - [x] Notifications
       - [x]  Created Devices
       - [x] Created Templates
       - [x] Flows
          - [x] Notifications
          - [x] Device Event in
          - [x] Switch
          - [x] Template
          - [x] Cumulative sum
          - [x] Device out
       - [x] Insecure publishing
            - [x] Verne 
       - [x] Profile
       - [x] User
       - [x] Map view
