### ISSUE TITLE
Backlog for pre-release v0.4.4-rc.1

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1772]
Read The docs (Temporary)
--------------------------

https://dojotdocs.readthedocs.io/en/release-v0.4.4/index.html
https://dojotdocs.readthedocs.io/pt_BR/release-v0.4.4/index.html

API documentation
--------------------------

https://dojot.github.io/auth/apiary_v0.4.4-rc.1.html
https://dojot.github.io/history/apiary_v0.4.4-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.4.4-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.4.4-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.4.4-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.4.4-rc.1.html
https://dojot.github.io/ejbca-rest/apiary_v0.4.4-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.4.4-rc.1.html 
https://dojot.github.io/cron/apiary_v0.4.4-rc.1.html

dojot/history
-------------

 - [x] dojot/history#93, linked issues dojot/dojot#1701: [release v0.4.4] History - Allow "First N" query
 - [x] dojot/history#94, linked issues dojot/dojot#1716: fix: stops when it receives a payload without attrs [0.4.4]

dojot/iotagent-mosca
--------------------

 - [x] dojot/iotagent-mosca#111: [v0.4.4] updated iotagent-nodejs lib
 - [x] dojot/iotagent-mosca#106, linked issues dojot/dojot#1732: fix: The CN inside certificate isn't checked

dojot/cron
----------

 - [x] dojot/cron#22, linked issues dojot/dojot#1730: [v0.4.4] - adapt cron service to support "dojot-module-nodejs" library at version 0.0.1-beta.9

dojot/gui
---------

 - [x] dojot/gui#661, linked issues dojot/dojot#1734: correcting the version
 - [ ] dojot/gui#640: Apply fixes from CodeFactor

dojot/data-broker
-----------------

 - [x] dojot/data-broker#100, linked issues dojot/dojot#1730: [v0.4.4] - upgrade "dojot-module-nodejs" library from 0.0.1-beta.4 to 0.0.1-beta.9

dojot/image-manager
-------------------

 - [x] dojot/image-manager#47, linked issues dojot/dojot#1584: [v0.4.4] Update documentation

dojot/device-manager
--------------------

 - [x] dojot/device-manager#164, linked issues dojot/dojot#1718: Change JSONIFY_PRETTYPRINT_REGULAR flask property to false [0.4.4]

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#304: [v0.4.4] Update dojot module
 - [x] dojot/flowbroker#303, linked issues dojot/dojot#1548: Upgrage kubernetes-client
 - [x] dojot/flowbroker#297, linked issues dojot/dojot#1584: [0.4.4] doc: review readmes and api 

dojot/iotagent-leshan
---------------------

 - [ ] dojot/iotagent-leshan#67, linked issues dojot/dojot#1502 dojot/dojot#1557 dojot/dojot#1704: [0.4.4] Add new features
 - [ ] dojot/iotagent-leshan#71: Changes all content request to use TLV
 - [ ] dojot/iotagent-leshan#63: [0.4.4] add pipenv and readme to simulator 
 - [ ] dojot/iotagent-leshan#61, linked issues dojot/dojot#1704: Feature discard invalid values
 - [ ] dojot/iotagent-leshan#57: Feature Flag Device Status
 - [ ] dojot/iotagent-leshan#56: Automatic Firmware Update

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#70, linked issues dojot/dojot#1770: Change name of apiGroups
 - [x] dojot/ansible-dojot#68, linked issues dojot/dojot#1741: Change rule for flowbroker (fixed in #1770 )
 - [x] dojot/ansible-dojot#64, linked issues dojot/dojot#1705: v0.4.4 upgrade k8s 1.17

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.4.4-rc.1
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.4.4-rc.1
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.4.4-rc.1
----
