### ISSUE TITLE
Backlog for pre-release v0.5.0-rc.1

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1774]
Read The docs  (Work in progress)
--------------------------

https://dojotdocs.readthedocs.io/en/release-v0.5.0/
https://dojotdocs.readthedocs.io/pt_BR/release-v0.5.0/

### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.5.0-rc.1.html
https://dojot.github.io/history/apiary_v0.5.0-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.5.0-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.5.0-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.5.0-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.5.0-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.5.0-rc.1.html
https://dojot.github.io/cron/apiary_v0.5.0-rc.1.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.5.0-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.5.0-rc.1.html

dojot/history
-------------

 - [x] dojot/history#101, linked issues dojot/dojot#1584: [release v0.5.0] Documentation improvement
 - [x] dojot/history#97, linked issues dojot/dojot#1688: [0.5.0] GET notifications: error in running the example
 - [ ] dojot/history#95, linked issues dojot/dojot#1716: fix: stops when it receives a payload without attrs [0.5.0]
 - [x] dojot/history#91, linked issues dojot/dojot#1701: [release] History - Allow "First N" query
 - [x] dojot/history#89, linked issues dojot/dojot#1516: [release] Persister - Workaround to be able to change the log level by API
 - [x] dojot/history#86, linked issues dojot/dojot#1504 dojot/dojot#1513 dojot/dojot#1515: [release/v0.5.0] Persister - Fix error when change log level
 - [x] dojot/history#81, linked issues dojot/dojot#1457: doc: fix wrong 404  [0.5.0]
 - [x] dojot/history#84, linked issues dojot/dojot#1513 dojot/dojot#1515: [release/v0.5.0] History - Correction of problems with the logger

dojot/iotagent-mosca
--------------------

 - [x] dojot/iotagent-mosca#112: [v0.5.0] updated iotagent-nodejs lib
 - [x] dojot/iotagent-mosca#109, linked issues dojot/dojot#1584: [v0.5.0] Change timestamp text

dojot/cron
----------

 - [x] dojot/cron#21, linked issues dojot/dojot#1730: [v0.5.0] - adapt cron service to support "dojot-module-nodejs" library at version 0.0.1-beta.9

dojot/gui
---------

 - [x] dojot/gui#655, linked issues dojot/dojot#1488: Report is not regenerated
 - [ ] dojot/gui#663, linked issues dojot/dojot#1721: Customizable URL for the application (**Mobilidade Elétrica**)
 - [x] dojot/gui#660, linked issues dojot/dojot#1734: correting the version
 - [x] dojot/gui#654, linked issues dojot/dojot#1486: Report does not have the identification of device

dojot/data-broker
-----------------

 - [x] dojot/data-broker#99, linked issues dojot/dojot#1730: [v0.5.0] - upgrade "dojot-module" library from 0.0.1-beta.5 to 0.0.1-beta.9
 - [x] dojot/data-broker#96, linked issues dojot/dojot#1584: [v0.5.0] Review APIB documentation
 - [x] dojot/data-broker#94, linked issues dojot/dojot#1584: [v0.5.0] Review documentation

dojot/image-manager
-------------------

 - [x] dojot/image-manager#45, linked issues dojot/dojot#1584: [v0.5.0] Update documentation

dojot/device-manager
--------------------

 - [x] dojot/device-manager#165, linked issues dojot/dojot#1718: Change JSONIFY_PRETTYPRINT_REGULAR flask property to false [0.5.0]
 - [x] dojot/device-manager#169, linked issues dojot/dojot#1729: [0.5.0] - Refresh "updated" column of template every time template structure changes
 - [x] dojot/device-manager#163, linked issues dojot/dojot#1584: [v0.5.0] Review documentation
 - [x] dojot/device-manager#162: test: fix version redis [v0.5.0]
 - [x] dojot/device-manager#157, linked issues dojot/dojot#1480: fix: Import/Export: Import fails  [0.5.0]

dojot/auth
----------

 - [x] dojot/auth#113, linked issues dojot/dojot#1584: [v0.5.0] Review README
 - [x] dojot/auth#106, linked issues dojot/dojot#1689 dojot/dojot#1584:  doc: Improve documentation  [0.5]

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#293, linked issues dojot/dojot#556: Add filter to node actuate
 - [x] dojot/flowbroker#294, linked issues dojot/dojot#1136: Add field to node ftp
 - [x] dojot/flowbroker#233, linked issues dojot/dojot#1141: Validate cron node
 - [x] dojot/flowbroker#305: [v0.5.0] Update dojot module
 - [x] dojot/flowbroker#302, linked issues dojot/dojot#1548: Upgrage kubernetes-client
 - [x] dojot/flowbroker#291, linked issues dojot/dojot#1584: [0.5.0] doc: review readmes and api 

dojot/iotagent-leshan
---------------------

 - [ ] dojot/iotagent-leshan#68, linked issues dojot/dojot#1502 dojot/dojot#1557 dojot/dojot#1704: [0.5.0] Add new features
 - [ ] dojot/iotagent-leshan#65:  [0.5.0] add pipenv and readme to simulator 
 - [ ] dojot/iotagent-leshan#61, linked issues dojot/dojot#1704: Feature discard invalid values
 - [ ] dojot/iotagent-leshan#57: Feature Flag Device Status
 - [ ] dojot/iotagent-leshan#56: Automatic Firmware Update

dojot/backstage
---------------

 - [x] dojot/backstage#56, linked issues dojot/dojot#1675: Changed sorting to ascending

dojot/dojot
-----------

 - [x] dojot/dojot#1757, linked issues dojot/dojot#1584: [v0.5.0] Update Kafka WS API documentation
 - [x] dojot/dojot#1742, linked issues dojot/dojot#1584: [v0.5.0] Review Locust Documentation
 - [x] dojot/dojot#1743, linked issues dojot/dojot#1584: [release v0.5.0][x509-identity-mgmt] A little bit about error responses in the API documentation
 - [x] dojot/dojot#1728, linked issues dojot/dojot#1714: [v0.5.0] Correct problems with the value 0
 - [ ] dojot/dojot#1719: [Release] fix supercronic processes created a lot
 - [x] dojot/dojot#1698, linked issues dojot/dojot#1584: [v0.5.0] Review VerneMQ and its plugins READMEs
 - [x] dojot/dojot#1695, linked issues dojot/dojot#1584: [v0.5.0] Review K2V documentation
 - [x] dojot/dojot#1699, linked issues dojot/dojot#1584: [v0.5.0] Review Loopback documentation
 - [x] dojot/dojot#1710: [v0.5.0] Change default value for V2K_KAFKA_COMPRESSION_CODEC
 - [x] dojot/dojot#1687, linked issues dojot/dojot#1681: Enhancements to generate_certs script
 - [x] dojot/dojot#1696, linked issues dojot/dojot#1584: [v0.5.0] Review V2K documentation

dojot/gui-v2
------------

 - [x] dojot/gui-v2#18, linked issues dojot/dojot#1767: Hide unused items
 - [x] dojot/gui-v2#11: chore: add branch/tag as docker tag 
 - [x] dojot/gui-v2#8: Revert "chore: add dockerhub and codecov in actions"
 - [x] dojot/gui-v2#7: chore: add dockerhub and codecov in actions
 - [x] dojot/gui-v2#6, linked issues dojot/dojot#1686: fix: Number of characters on the y-axis scale
 - [x] dojot/gui-v2#5, linked issues dojot/dojot#1684: fix: Line Chart y-axis scale
 - [ ] dojot/gui-v2#3: Apply fixes from CodeFactor
 - [x] dojot/gui-v2#2, linked issues dojot/dojot#1694: fix: clear dashboard context at logout

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#189, linked issues dojot/dojot#1722: [v0.5.0] update docker-compose file version to 3.8
 - [x] dojot/docker-compose#187: [0.5] apigw restart: always
 - [x] dojot/docker-compose#181: doc: comment to disable insecure mode without TLS.
 - [x] dojot/docker-compose#180: chore: change to alpha4,add gui-v2 and kafka2ftp
 - [x] dojot/docker-compose#178, linked issues dojot/dojot#1648: fix: add missing http port for leshan [v0.5.0]
 - [x] dojot/docker-compose#175, linked issues dojot/dojot#1631: Changing Kafka's image to stay the same on kubernetes
 - [x] dojot/docker-compose#172, linked issues dojot/dojot#1585 dojot/dojot#1484: fix kafka hostname
 - [x] dojot/docker-compose#169, linked issues dojot/dojot#1605 dojot/dojot#1604: chore: change mosca to use x509-identity-m
 - [x] dojot/docker-compose#170, linked issues dojot/dojot#1585 dojot/dojot#1484: Fix in MqTT service volumes
 - [x] dojot/docker-compose#157: Inclusion of new iotagent-mqtt and its peripherals
 - [x] dojot/docker-compose#167: Defining tag v0.5.0-alpha.3 for docker images
 - [x] dojot/docker-compose#166, linked issues dojot/dojot#1585 dojot/dojot#1484: fix zookeeper volumes (v0.5.0)
 - [ ] dojot/docker-compose#161: chore: set timeout for kafka-ws
 - [ ] dojot/docker-compose#159, linked issues dojot/dojot#1388: chore: add auth for  /graphql route and add new route /graphql-auth 
 - [x] dojot/docker-compose#156, linked issues dojot/dojot#1469 dojot/dojot#1459 dojot/dojot#1484: Inclusion of the x509-identity-mgmt and kafka-ws components
 - [x] dojot/docker-compose#153, linked issues dojot/dojot#1414: chore: https example
 - [x] dojot/docker-compose#151, linked issues dojot/dojot#1437: chore: upgrade to kong 2.0.3
 - [ ] dojot/docker-compose#148: bugfix in certificate renewal

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#71, linked issues dojot/dojot#1770: Changing apiGroups
 - [x] dojot/ansible-dojot#69: chore: change to public img for gui-v2
 - [x] dojot/ansible-dojot#67, linked issues dojot/dojot#1741: Changing rule for flowbroker
 - [x] dojot/ansible-dojot#66: [v0.5.0] Add utility scripts
 - [x] dojot/ansible-dojot#63, linked issues dojot/dojot#1680: NodePort 1883 will not be mapped if insecure mode is disabled
 - [x] dojot/ansible-dojot#62: zookeeper node affinity label

 
----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.5.0-rc.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.5.0-rc.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.5.0-rc.1
----
