### ISSUE TITLE
Backlog for pre-release v0.5.0-rc.2

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1862]
Read The docs  (Work in progress)
--------------------------

https://dojotdocs.readthedocs.io/en/release-v0.5.0/
https://dojotdocs.readthedocs.io/pt_BR/release-v0.5.0/

### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.5.0-rc.2.html
https://dojot.github.io/history/apiary_v0.5.0-rc.2.html
https://dojot.github.io/device-manager/apiary_v0.5.0-rc.2.html
https://dojot.github.io/image-manager/apiary_v0.5.0-rc.2.html
https://dojot.github.io/flowbroker/apiary_v0.5.0-rc.2.html
https://dojot.github.io/data-broker/apiary_v0.5.0-rc.2.html
https://dojot.github.io/data-manager/apiary_v0.5.0-rc.2.html
https://dojot.github.io/cron/apiary_v0.5.0-rc.2.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.5.0-rc.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.5.0-rc.2.html

dojot/gui
---------

 - [ ] dojot/gui#683, linked issues dojot/dojot#1191: Attribute metadata are not specialized in creating or changing device
 - [x] dojot/gui#688, linked issues dojot/dojot#1777: fix: Import CSS fix

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#312, linked issues dojot/dojot#1803 dojot/dojot#1809: Fix problem when flowbroker and/or remote node are restarted [v0.5.0]
 - [x] dojot/flowbroker#308, linked issues dojot/dojot#1803: Fix remove node [v0.5.0]

dojot/iotagent-leshan
---------------------

 - [ ] dojot/iotagent-leshan#77, linked issues dojot/dojot#1818: [0.5.0] - Fix firmware update bug

dojot/dojot
-----------

 - [x] dojot/dojot#1861: fix kafka-ws entrypoint
 - [ ] dojot/dojot#1839: [realease/v0.5.0] Added entrypoint script
 - [x] dojot/dojot#1836, linked issues dojot/dojot#1825: [Release-v0.5.0] End kafka-ws process when a rejected promise is not handled anywhere
 - [ ] dojot/dojot#1785: [v0.5.0]  Remove token codecov
 - [x] dojot/dojot#1763: [v0.5.0] Review readme from kafka2ftp

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#26: fix github actions docker push
 - [x] dojot/gui-v2#23, linked issues dojot/dojot#1771: Errors should be shown when it is not possible to login
 - [x] dojot/gui-v2#25, linked issues dojot/dojot#1674: "Valor" field accepts negative values
 - [x] dojot/gui-v2#21: Update README.md
 - [x] dojot/gui-v2#24, linked issues dojot/dojot#1778: fix: problem when displaying a json in the table
 - [x] dojot/gui-v2#20: chore: fix the nginx version

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#192, linked issues dojot/dojot#1780: set log file size for some services

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#75, linked issues dojot/dojot#1827: Update requirements.txt
 - [x] dojot/ansible-dojot#79: fix env kafka-ws and bump to v0.5.0-rc.2
 
 
 ----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.5.0-rc.2
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.5.0-rc.2
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.5.0-rc.2
----
