### ISSUE TITLE
Backlog for pre-release v0.5.1-rc.2

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1917]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.5.1-rc.2.html
https://dojot.github.io/history/apiary_v0.5.1-rc.2.html
https://dojot.github.io/device-manager/apiary_v0.5.1-rc.2.html
https://dojot.github.io/image-manager/apiary_v0.5.1-rc.2.html
https://dojot.github.io/flowbroker/apiary_v0.5.1-rc.2.html
https://dojot.github.io/data-broker/apiary_v0.5.1-rc.2.html
https://dojot.github.io/data-manager/apiary_v0.5.1-rc.2.html
https://dojot.github.io/cron/apiary_v0.5.1-rc.2.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.5.1-rc.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.5.1-rc.2.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.5.1-rc.2

dojot/dojot
-----------

 - [x] dojot/dojot#1915, linked issues #1916: [influxdb-retriever] Allow Reserved for date-time
 - [x] dojot/dojot#1909, linked issues #1912: [influxdb-retriever] Fix:  Pagination and offset
 - [ ] dojot/dojot#1906: [InfluxDB-Retriever/Storer] Disable validate responses,  fix a wrong param webUtils, remove drop and remove unused configs

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#209: [v0.5.1] influx docker log file cycle 

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#92: Fixing nginx syntax error
 - [ ] dojot/ansible-dojot#90: [v0.5.1] metrics deploy order
 - [x] dojot/ansible-dojot#88, linked issues dojot/dojot#1883: [v0.5.1] add influxdb, storer and retriever

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.5.1-rc.2
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.5.1-rc.2
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.5.1-rc.2
----
