### ISSUE TITLE
Backlog for pre-release v0.5.2-rc.1

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1948]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.5.2-rc.1.html
https://dojot.github.io/history/apiary_v0.5.2-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.5.2-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.5.2-rc.1.html 
https://dojot.github.io/flowbroker/apiary_v0.5.2-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.5.2-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.5.2-rc.1.html
https://dojot.github.io/cron/apiary_v0.5.2-rc.1.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.5.2-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.5.2-rc.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.5.2-rc.1

dojot/history
-------------

 - [ ] dojot/history#105, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development 
 - [ ] dojot/history#104, linked issues dojot/dojot#1879: Licensed the 'history' and 'persister' services under Apache-2.0 License

dojot/iotagent-mosca
--------------------

 - [ ] dojot/iotagent-mosca#120, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/iotagent-mosca#119, linked issues dojot/dojot#1879: change badge license
 - [ ] dojot/iotagent-mosca#115, linked issues dojot/dojot#1879: license and version change

dojot/cron
----------

 - [ ] dojot/cron#31, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development 
 - [ ] dojot/cron#27: Changed license from GPL-3.0 to Apache-2.0

dojot/gui
---------

 - [ ] dojot/gui#711, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development

dojot/data-broker
-----------------

 - [ ] dojot/data-broker#118, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/data-broker#113, linked issues dojot/dojot#1879: change license badge
 - [ ] dojot/data-broker#109, linked issues dojot/dojot#1879: license and version change

dojot/image-manager
-------------------

 - [ ] dojot/image-manager#51, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development 
 - [ ] dojot/image-manager#50, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0

dojot/device-manager
--------------------

 - [ ] dojot/device-manager#175, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development 
 - [ ] dojot/device-manager#172, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0

dojot/auth
----------

 - [ ] dojot/auth#118, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development 
 - [ ] dojot/auth#117, linked issues dojot/dojot#1879: Fixed the service version
 - [ ] dojot/auth#115, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0

dojot/kong
----------

 - [ ] dojot/kong#25, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/kong#24, linked issues dojot/dojot#1879: Changed license from GPL-v3 to Apache

dojot/flowbroker
----------------

 - [ ] dojot/flowbroker#333, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/flowbroker#327, linked issues dojot/dojot#1879: change license examples
 - [ ] dojot/flowbroker#326: Changed the license badge to Apache-2.0
 - [ ] dojot/flowbroker#322, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0

dojot/data-manager
------------------

 - [ ] dojot/data-manager#36, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/data-manager#33, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0

dojot/iotagent-leshan
---------------------

 - [ ] dojot/iotagent-leshan#88, linked issues dojot/dojot#1930: [Rel-0.5.2] Fix the .jar name/version in Dockerfile
 - [ ] dojot/iotagent-leshan#86, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/iotagent-leshan#82, linked issues dojot/dojot#1879: license and version change

dojot/backstage
---------------

 - [ ] dojot/backstage#74, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development 
 - [ ] dojot/backstage#67, linked issues dojot/dojot#1879: [dev] Changed license to Apache 2.0 

dojot/dojot
-----------

 - [ ] dojot/dojot#1946, linked issues: fixed vernemq script
 - [ ] dojot/dojot#1936, linked issues dojot/dojot#1930: [v0.5.2] some fix after update lib version
 - [ ] dojot/dojot#1932, linked issues #1930: [v0.5.2] Cherry-picking licenses from development
 - [ ] dojot/dojot#1933, linked issues #1880: [v0.5.2] vernemq image build
 - [ ] dojot/dojot#1922, linked issues dojot/dojot#1879: [x509-identity-mgmt] license and version change
 - [ ] dojot/dojot#1923, linked issues dojot/dojot#1879: Updated Readme file with licenses information
 - [ ] dojot/dojot#1921, linked issues dojot/dojot#1879: Updated README file and added LICENSE file
 - [ ] dojot/dojot#1920, linked issues dojot/dojot#1879: Licensed the dojot tools under Apache License, version 2.0
 - [ ] dojot/dojot#1919, linked issues dojot/dojot#1879: Licensed 'Dojot Load Test' under Apache License, Version 2.0
 - [ ] dojot/dojot#1900, linked issues #1879: [dev] Changed kafka2ftp license to Apache 2.0, remove old library and add example
 - [ ] dojot/dojot#1873, linked issues: Changed the k2v license to Apache-2.0
 - [ ] dojot/dojot#1872, linked issues: Changed v2k license to Apache-2.0
 - [ ] dojot/dojot#1871, linked issues: Changed kafka-ws license to Apache 2.0

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#34, linked issues dojot/dojot#1930: [v0.5.2] Cherry-picking licenses from development

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#219, linked issues #1958:  Removes verification that it is onboarded and changes to maximum attempts
 - [ ] dojot/docker-compose#217: Merge version v0.5.1 from branch release/v0.5.1 to branch master
 - [ ] dojot/docker-compose#211: license update

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.5.2-rc.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.5.2-rc.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.5.2-rc.1
----
