### ISSUE TITLE
Backlog for pre-release v0.6.0-rc.1

### ISSUE THREAD

**Issue by andersonluisribeiro** [dojot/dojot#2000]
Backlog
---------------------

### API Documentations:

https://dojot.github.io/auth/apiary_v0.6.0-rc.1.html
https://dojot.github.io/history/apiary_v0.6.0-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.6.0-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.6.0-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.6.0-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.6.0-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.6.0-rc.1.html
https://dojot.github.io/cron/apiary_v0.6.0-rc.1.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.6.0-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.6.0-rc.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.6.0-rc.1

### Full Backlog:

dojot/history
-------------

 - [ ] dojot/history#104, linked issues dojot/dojot#1879: Licensed the 'history' and 'persister' services under Apache-2.0 License
 - [x] dojot/history#100, linked issues dojot/dojot#1584: [development] Documentation improvement
 - [ ] dojot/history#98, linked issues dojot/dojot#1688: [dev] GET notifications: error in running the example
 - [x] dojot/history#96, linked issues dojot/dojot#1716: fix: stops when it receives a payload without attrs [dev]
 - [x] dojot/history#92, linked issues dojot/dojot#1701: [development] History - Allow "First N" query
 - [x] dojot/history#90, linked issues dojot/dojot#1516: [development] Persister - Workaround to be able to change the log level by API
 - [x] dojot/history#87, linked issues dojot/dojot#1504 dojot/dojot#1513 dojot/dojot#1515: [development] Persister - Fix error when change log level
 - [x] dojot/history#83, linked issues dojot/dojot#1457: doc: fix wrong 404  [dev]
 - [ ] dojot/history#85, linked issues dojot/dojot#1513 dojot/dojot#1515: [development] History - Correction of problems with the logger
 - [x] dojot/history#79, linked issues dojot/dojot#1457: doc: More detail on api documentation  [dev]
 - [ ] dojot/history#70, linked issues #L126: fix: add index and fix event create 
 - [ ] dojot/history#75: chore: fix pip version - travis

dojot/iotagent-mosca
--------------------

 - [ ] dojot/iotagent-mosca#119, linked issues dojot/dojot#1879: change badge license
 - [x] dojot/iotagent-mosca#115, linked issues dojot/dojot#1879: license and version change
 - [ ] dojot/iotagent-mosca#110: [developement] Iotagent nodejs update
 - [x] dojot/iotagent-mosca#108, linked issues dojot/dojot#1584: [dev] Change timestamp text
 - [ ] dojot/iotagent-mosca#103, linked issues dojot/dojot#1605:  chore: update to use the new X.509 Identity Management  (#102)
 - [ ] dojot/iotagent-mosca#102, linked issues dojot/dojot#1605 dojot/dojot#1201 dojot/dojot#1235:  chore: update to use the new X.509 Identity Management 
 - [ ] dojot/iotagent-mosca#102, linked issues dojot/dojot#1605 dojot/dojot#1201 dojot/dojot#1235:  chore: update to use the new X.509 Identity Management 

dojot/cron
----------

 - [ ] dojot/cron#32, linked issues dojot/dojot#1913: Remove travis and make changes to use github actions
 - [ ] dojot/cron#27: Changed license from GPL-3.0 to Apache-2.0
 - [ ] dojot/cron#20, linked issues dojot/dojot#1730: [dev] - adapt cron service to support "dojot-module-nodejs" library at version 0.0.1-beta.9

dojot/gui
---------

 - [ ] dojot/gui#713, linked issues dojot/dojot#1808: Adding better message errors
 - [ ] dojot/gui#714, linked issues dojot/dojot#1810: Changes the notification date handler to its view component
 - [ ] dojot/gui#696, linked issues dojot/dojot#1815: firmware update template
 - [ ] dojot/gui#700, linked issues dojot/dojot#1822: metadata parameter is shown as undefined
 - [ ] dojot/gui#710, linked issues dojot/dojot#1897: Remove test e2e
 - [ ] dojot/gui#706, linked issues dojot/dojot#1879: Update license-exceptions.json and package license
 - [ ] dojot/gui#702, linked issues dojot/dojot#1879: [dev] Changed license to Apache 2.0 
 - [ ] dojot/gui#684, linked issues dojot/dojot#1191: Attribute metadata are not specialized in creating or changing device
 - [ ] dojot/gui#686, linked issues dojot/dojot#1738: Feat: Actuation command in device details
 - [ ] dojot/gui#690, linked issues dojot/dojot#1777: fix: Import CSS fix
 - [x] dojot/gui#656, linked issues dojot/dojot#1488: Report is not regenerated
 - [ ] dojot/gui#662, linked issues dojot/dojot#1721: Customizable URL for the application
 - [x] dojot/gui#659, linked issues dojot/dojot#1734: correcting the version
 - [x] dojot/gui#651, linked issues dojot/dojot#1486: Report does not have the identification of device
 - [ ] dojot/gui#635, linked issues #613: Revert "fix: date correction on the device chart"
 - [ ] dojot/gui#632: fix some erros in testes
 - [ ] dojot/gui#631: fix: codecept
 - [x] dojot/gui#629, linked issues dojot/dojot#1508: fix: Error showing Tenant
 - [ ] dojot/gui#613, linked issues dojot/dojot#1464: fix: date correction on the device chart
 - [ ] dojot/gui#611, linked issues dojot/dojot#1388 #36 #99: chore: add auth for  /graphql route and change to /graphql-auth [dev]
 - [x] dojot/gui#612, linked issues dojot/dojot#1212: correcting the flow date
 - [ ] dojot/gui#609: support for the new x509-identity-mgmt component (merge development)
 - [x] dojot/gui#610, linked issues dojot/dojot#1165: Validation for importing firmware

dojot/data-broker
-----------------

 - [ ] dojot/data-broker#119, linked issues dojot/dojot#1879 dojot/dojot#1930: Fix: change npm dojot-modules lib version 
 - [ ] dojot/data-broker#113, linked issues dojot/dojot#1879: change license badge
 - [ ] dojot/data-broker#109, linked issues dojot/dojot#1879: license and version change
 - [ ] dojot/data-broker#98, linked issues dojot/dojot#1730: [dev] - upgrade "dojot-module" library from 0.0.1-beta.5 to 0.0.1-beta.9
 - [ ] dojot/data-broker#97, linked issues dojot/dojot#1584: [dev] Review documentation
 - [ ] dojot/data-broker#96, linked issues dojot/dojot#1584: [v0.5.0] Review APIB documentation
 - [ ] dojot/data-broker#94, linked issues dojot/dojot#1584: [v0.5.0] Review documentation

dojot/image-manager
-------------------

 - [ ] dojot/image-manager#50, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0
 - [ ] dojot/image-manager#46, linked issues dojot/dojot#1584: [dev] Update documentation

dojot/device-manager
--------------------

 - [ ] dojot/device-manager#178: fix: Fixes all libs versions  in requirements
 - [ ] dojot/device-manager#172, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0
 - [ ] dojot/device-manager#166, linked issues dojot/dojot#1718: Change JSONIFY_PRETTYPRINT_REGULAR flask property to false [Dev]
 - [ ] dojot/device-manager#167, linked issues dojot/dojot#1729: [Dev] - Refresh "updated" column of template every time template structure changes
 - [ ] dojot/device-manager#160, linked issues dojot/dojot#1584: [dev] Review documentation
 - [ ] dojot/device-manager#161: test: fix version redis [dev]
 - [ ] dojot/device-manager#158, linked issues dojot/dojot#1480: fix: Import/Export: Import fails [dev]
 - [ ] dojot/device-manager#154: chore: fix pip version - travis

dojot/auth
----------

 - [ ] dojot/auth#117, linked issues dojot/dojot#1879: Fixed the service version
 - [ ] dojot/auth#115, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0
 - [ ] dojot/auth#112, linked issues dojot/dojot#1584: [dev] Review README
 - [ ] dojot/auth#107, linked issues dojot/dojot#1689 dojot/dojot#1584:  doc: Improve documentation  [dev]
 - [ ] dojot/auth#99, linked issues dojot/dojot#1388 #36: chore: add auth for  /graphql route  [dev]
 - [ ] dojot/auth#98: support for the new x509-identity-mgmt component (merge development)

dojot/kong
----------

 - [ ] dojot/kong#23: Upgrade kong version to 2.2
 - [ ] dojot/kong#24, linked issues dojot/dojot#1879: Changed license from GPL-v3 to Apache
 - [ ] dojot/kong#17, linked issues dojot/dojot#1437 dojot/dojot#1135: chore: upgrade to kong 2.0.3

dojot/flowbroker
----------------

 - [ ] dojot/flowbroker#334, linked issues dojot/dojot#1879 dojot/dojot#1930: Change lib version in examples
 - [ ] dojot/flowbroker#332, linked issues #331: Revert "Revert "Fix problem when flowbroker and/or remote node are restarted [dev]""
 - [ ] dojot/flowbroker#331, linked issues #314: Revert "Fix problem when flowbroker and/or remote node are restarted [dev]"
 - [ ] dojot/flowbroker#314, linked issues dojot/dojot#1809 dojot/dojot#1803: Fix problem when flowbroker and/or remote node are restarted [dev]
 - [ ] dojot/flowbroker#327, linked issues dojot/dojot#1879: change license examples
 - [ ] dojot/flowbroker#326: Changed the license badge to Apache-2.0
 - [ ] dojot/flowbroker#322, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0
 - [ ] dojot/flowbroker#309, linked issues dojot/dojot#1803: Fix remove node [dev]
 - [ ] dojot/flowbroker#288: [dev] Update dojot module
 - [ ] dojot/flowbroker#306, linked issues dojot/dojot#1141: Change regex validaton in cron node
 - [ ] dojot/flowbroker#289, linked issues dojot/dojot#1548: Upgrade kubernetes-client
 - [ ] dojot/flowbroker#295, linked issues dojot/dojot#1136: Add field to node ftp
 - [ ] dojot/flowbroker#299: Bump lodash from 4.17.11 to 4.17.20 in /lib
 - [ ] dojot/flowbroker#298: Bump lodash from 4.17.11 to 4.17.20 in /contextManager
 - [ ] dojot/flowbroker#296, linked issues dojot/dojot#1584: [dev] doc: review readmes and api
 - [ ] dojot/flowbroker#287, linked issues dojot/dojot#556: Remove from list all devices when it's not have actuate attribute
 - [ ] dojot/flowbroker#282, linked issues dojot/dojot#1645 dojot/dojot#1650: fix: some undefined  variables in http node [dev] 
 - [ ] dojot/flowbroker#257: chore: upgrade libs examples [dev]
 - [ ] dojot/flowbroker#245, linked issues dojot/dojot#1156: Fixes portuguese translation
 - [ ] dojot/flowbroker#271, linked issues dojot/dojot#1298: Remove request body as a mandatory field (to dev) 
 - [ ] dojot/flowbroker#273, linked issues dojot/dojot#1377: Add parameter to del remote node (to dev)
 - [ ] dojot/flowbroker#261, linked issues dojot/dojot#1565: feat: Changed to process messages in parallel [dev]

dojot/data-manager
------------------

 - [ ] dojot/data-manager#33, linked issues dojot/dojot#1879: Changed license from GPL-3.0 to Apache-2.0

dojot/iotagent-leshan
---------------------

 - [ ] dojot/iotagent-leshan#87, linked issues dojot/dojot#1930: Fix the .jar name/version in Dockerfile
 - [ ] dojot/iotagent-leshan#82, linked issues dojot/dojot#1879: license and version change
 - [ ] dojot/iotagent-leshan#76, linked issues dojot/dojot#1818: [dojot/dojot/1818] - fix firmware update bug
 - [ ] dojot/iotagent-leshan#66, linked issues dojot/dojot#1502 dojot/dojot#1557 dojot/dojot#1704: [Dev] Add new features
 - [ ] dojot/iotagent-leshan#64: [dev] add pipenv and readme to simulator 
 - [ ] dojot/iotagent-leshan#61, linked issues dojot/dojot#1704: Feature discard invalid values
 - [ ] dojot/iotagent-leshan#57: Feature Flag Device Status
 - [ ] dojot/iotagent-leshan#56: Automatic Firmware Update

dojot/backstage
---------------

 - [ ] dojot/backstage#75, linked issues dojot/dojot#1852: Feat: Added support of static attributes to the dashboard
 - [ ] dojot/backstage#67, linked issues dojot/dojot#1879: [dev] Changed license to Apache 2.0 
 - [ ] dojot/backstage#56, linked issues dojot/dojot#1675: Changed sorting to ascending
 - [ ] dojot/backstage#53, linked issues dojot/dojot#1672: Ordering values for the dashboard
 - [ ] dojot/backstage#51, linked issues dojot/dojot#1567:  feat: Change to handle dates in seconds, milliseconds and microseconds
 - [ ] dojot/backstage#49, linked issues dojot/dojot#1567: Release/v0.5.0 alpha
 - [ ] dojot/backstage#46, linked issues dojot/dojot#1379: feat: New query to consult history for the dashboard
 - [ ] dojot/backstage#42: add fix from dev
 - [ ] dojot/backstage#40, linked issues dojot/dojot#1388: feat: [features in development] add get device by id, get devices and get history and save user data 
 - [ ] dojot/backstage#37: Support for the new x509-identity-mgmt component

dojot/dojot
-----------

 - [ ] dojot/dojot#1984, linked issues: [v0.6] fix healthcheck kafkaws v0.6
 - [ ] dojot/dojot#1974, linked issues #1973: [v0.6.0] remove terminus
 - [ ] dojot/dojot#1972, linked issues: [v0.6.0] Fixed configManager json build
 - [ ] dojot/dojot#1959, linked issues dojot/dojot#1958: [InfluxDB][Example] fix: Removes verification that it is onboarded and changes to maximum attempts
 - [ ] dojot/dojot#1813, linked issues #1629: feat: add cert-sidecar
 - [ ] dojot/dojot#1950, linked issues: [dev] fix vernemq, vernemq.sh script and notice
 - [ ] dojot/dojot#1934, linked issues: [influxdb-storer] Improve readme
 - [ ] dojot/dojot#1931, linked issues #1880: [development] build new vernemq docker image
 - [ ] dojot/dojot#1922, linked issues dojot/dojot#1879: [x509-identity-mgmt] license and version change
 - [ ] dojot/dojot#1924, linked issues: [x509-identity-mgmt] Improved EJBCA configuration scripts
 - [ ] dojot/dojot#1923, linked issues dojot/dojot#1879: Updated Readme file with licenses information
 - [ ] dojot/dojot#1921, linked issues dojot/dojot#1879: Updated README file and added LICENSE file
 - [ ] dojot/dojot#1920, linked issues dojot/dojot#1879: Licensed the dojot tools under Apache License, version 2.0
 - [ ] dojot/dojot#1919, linked issues dojot/dojot#1879: Licensed 'Dojot Load Test' under Apache License, Version 2.0
 - [ ] dojot/dojot#1914, linked issues #1916: [dev] [influxdb-retriever] Allow Reserved for date-time
 - [ ] dojot/dojot#1910, linked issues #1912: [dev - influxdb-retriever] Fix: Pagination and offset
 - [ ] dojot/dojot#1905, linked issues: [dev] [InfluxDB-Retriever/Storer] Disable validate responses,  fix a wrong param webUtils, remove drop and remove unused configs
 - [ ] dojot/dojot#1900, linked issues #1879: [dev] Changed kafka2ftp license to Apache 2.0, remove old library and add example
 - [ ] dojot/dojot#1858, linked issues #1819: [dev] add influxdb store and retriever
 - [ ] dojot/dojot#1893, linked issues #1879: [dev] Remove unused service for latency
 - [ ] dojot/dojot#1873, linked issues: Changed the k2v license to Apache-2.0
 - [ ] dojot/dojot#1872, linked issues: Changed v2k license to Apache-2.0
 - [ ] dojot/dojot#1871, linked issues: Changed kafka-ws license to Apache 2.0
 - [ ] dojot/dojot#1867, linked issues: [dev kafkaws] Kafkaws graceful shutdown
 - [ ] dojot/dojot#1824, linked issues: [dev] added healthcheck to kafka ws
 - [ ] dojot/dojot#1866, linked issues: [locust] Change generate-certs base image to the Locust one
 - [ ] dojot/dojot#1855, linked issues dojot/dojot#1849: [k2v] Add Health Check and Graceful Shutdown
 - [ ] dojot/dojot#1850, linked issues dojot/dojot#1848 dojot/dojot#1846: [v2k] Add Health Check and Graceful Shutdown
 - [ ] dojot/dojot#1842, linked issues: [development] Fix and improvement kafkaWS
 - [ ] dojot/dojot#1828, linked issues dojot/dojot#1733: [k2v] Add ConfigManager
 - [ ] dojot/dojot#1794, linked issues: [development] add configManager to kafkaWS
 - [ ] dojot/dojot#1816, linked issues: [v2k-bridge] Correct links in README
 - [ ] dojot/dojot#1781, linked issues: Fix env var in default.conf
 - [ ] dojot/dojot#1793, linked issues: Fix: codecov v2k 
 - [ ] dojot/dojot#1784, linked issues: [dev] remove token codecov
 - [ ] dojot/dojot#1779, linked issues dojot/dojot#1733: Add ConfigManager
 - [ ] dojot/dojot#1762, linked issues #1584: [dev] Review readme from kafka2ftp
 - [ ] dojot/dojot#1758, linked issues dojot/dojot#1584: [dev] Review Locust Documentation
 - [ ] dojot/dojot#1759, linked issues dojot/dojot#1584: [dev] Fix in Kafka WS documentation
 - [ ] dojot/dojot#1748, linked issues dojot/dojot#1584: [dev] Update Kafka WS API documentation
 - [ ] dojot/dojot#1744, linked issues dojot/dojot#1584: [development][x509-identity-mgmt] A little bit about error responses in the API documentation
 - [ ] dojot/dojot#1727, linked issues dojot/dojot#1714: [dev] Correct problems with the value 0
 - [ ] dojot/dojot#1720, linked issues: [Development] fix supercronic processes created a lot
 - [ ] dojot/dojot#1709, linked issues dojot/dojot#1584: [dev] Review VerneMQ and its plugins' READMEs
 - [ ] dojot/dojot#1708, linked issues dojot/dojot#1584: [dev] Review V2K documentation
 - [ ] dojot/dojot#1707, linked issues dojot/dojot#1584: [dev] Review K2V documentation
 - [ ] dojot/dojot#1706, linked issues dojot/dojot#1584: [dev] Review Loopback documentation
 - [ ] dojot/dojot#1580: [development]: crl download fix
 - [ ] dojot/dojot#1667, linked issues dojot/dojot#1584: [development] Update IoT Agent MqTT docs
 - [ ] dojot/dojot#1668, linked issues dojot/dojot#1637: [dev] Add bool operator
 - [ ] dojot/dojot#1642, linked issues dojot/dojot#1626: [dev] [locust] Add Locust Exporter
 - [ ] dojot/dojot#1583: [release] Add milliseconds to v2k timestamp
 - [ ] dojot/dojot#1639: [dev] [locust] Correct --remove behaviour
 - [ ] dojot/dojot#1658, linked issues dojot/dojot#1651: [dev] Fix parameter name parsing
 - [ ] dojot/dojot#1647, linked issues dojot/dojot#1635: [dev] Fix number parsing
 - [ ] dojot/dojot#1656, linked issues dojot/dojot#1621: [dev] Enhance fields documentation
 - [ ] dojot/dojot#1592: Add configuration to name tag for kafka-ws
 - [ ] dojot/dojot#1619: Tool for generating device certificates
 - [ ] dojot/dojot#1622: doc: fix default Kafka consumption topic variable value
 - [ ] dojot/dojot#1623: improve debug when trying send msg to kafka 
 - [ ] dojot/dojot#1607: [dev] Fix Locust Docker files
 - [ ] dojot/dojot#1598: Tool for generating dummy certificates
 - [ ] dojot/dojot#1620, linked issues #1616: improved documentation x509-identity-mnmt (branch "development")
 - [ ] dojot/dojot#1618: [feature] [dev] Add new Kafka WS example that works with Dojot environment
 - [ ] dojot/dojot#1612, linked issues #1598: update codecov settings
 - [ ] dojot/dojot#1606: [dev] Add environment variable to enable requesting certificates from client
 - [ ] dojot/dojot#1608: chore: remove sdk from dojot/dojot and add to a new repository
 - [ ] dojot/dojot#1595: doc: mosquitto_sub wrong topic
 - [ ] dojot/dojot#1577, linked issues dojot/dojot#1596: Add EJBCA variable default value in K2V
 - [ ] dojot/dojot#1569: [enhancement] Small fixes in K2V and V2K
 - [ ] dojot/dojot#1570: Update development branch (merge from release/v0.5.0-alpha)
 - [ ] dojot/dojot#1566: [kafka-ws] Small fixes
 - [ ] dojot/dojot#1563: chore: Add note kong
 - [ ] dojot/dojot#1543: [fix] Gevent version is not fixed in Locust
 - [ ] dojot/dojot#1537: Feature: sdk logger with default console transport
 - [ ] dojot/dojot#1532: [fix] Endpoint change to facilitate API Gateway redirection
 - [ ] dojot/dojot#1530: [Fix] to verify the token returned by Redis
 - [ ] dojot/dojot#1519: [bugfix][kafka-ws] Implementation of the ticket mechanism
 - [ ] dojot/dojot#1518: Epic 100k mqtt devices
 - [ ] dojot/dojot#1512: Merge branch 'master' into 'development'
 - [ ] dojot/dojot#1511: Apply fixes from CodeFactor
 - [ ] dojot/dojot#1510: Merge branch 'epic-kafka-ws' into 'development'
 - [ ] dojot/dojot#1509: Epic routing
 - [ ] dojot/dojot#1507: Apply fixes from CodeFactor
 - [ ] dojot/dojot#1506: Merge branch 'epic-x509-identities' into development
 - [ ] dojot/dojot#1420, linked issues #1401: feat: [connector/kafka2ftp] New service kafka2ftp
 - [ ] dojot/dojot#1376: doc: add templates and codeowners
 - [ ] dojot/dojot#7: Updates readme with a more friendly message

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#39: Added Edit function to card
 - [ ] dojot/gui-v2#37, linked issues dojot/dojot#1961: Form wizard
 - [ ] dojot/gui-v2#36, linked issues dojot/dojot#1852: Map widget
 - [ ] dojot/gui-v2#35, linked issues dojot/dojot#1962: Adding Unit tests on Utils classes
 - [ ] dojot/gui-v2#27, linked issues dojot/dojot#1869: Adding Ordering in SimpleTable component
 - [ ] dojot/gui-v2#29: The behavior between the fields is different
 - [ ] dojot/gui-v2#31, linked issues dojot/dojot#1860 dojot/dojot#1771: Dashboard Login - Should be checked the error validation on handleSubmit
 - [ ] dojot/gui-v2#30, linked issues dojot/dojot#1879: Update license-exceptions.json and badge 
 - [ ] dojot/gui-v2#28, linked issues dojot/dojot#1879: [dev] Changed license to Apache 2.0 
 - [ ] dojot/gui-v2#26: fix github actions docker push
 - [ ] dojot/gui-v2#23, linked issues dojot/dojot#1771: Errors should be shown when it is not possible to login
 - [ ] dojot/gui-v2#25, linked issues dojot/dojot#1674: "Valor" field accepts negative values
 - [ ] dojot/gui-v2#21: Update README.md
 - [ ] dojot/gui-v2#24, linked issues dojot/dojot#1778: fix: problem when displaying a json in the table
 - [ ] dojot/gui-v2#20: chore: fix the nginx version
 - [ ] dojot/gui-v2#18, linked issues dojot/dojot#1767: Hide unused items
 - [ ] dojot/gui-v2#11: chore: add branch/tag as docker tag 
 - [ ] dojot/gui-v2#8: Revert "chore: add dockerhub and codecov in actions"
 - [ ] dojot/gui-v2#7: chore: add dockerhub and codecov in actions
 - [ ] dojot/gui-v2#6, linked issues dojot/dojot#1686: fix: Number of characters on the y-axis scale
 - [ ] dojot/gui-v2#5, linked issues dojot/dojot#1684: fix: Line Chart y-axis scale
 - [ ] dojot/gui-v2#3: Apply fixes from CodeFactor
 - [ ] dojot/gui-v2#2, linked issues dojot/dojot#1694: fix: clear dashboard context at logout

dojot/docs
----------

 - [ ] dojot/docs#122: add license
 - [ ] dojot/docs#120: changes to avoid confusion for new users
 - [ ] dojot/docs#119: Update components-and-apis.po
 - [ ] dojot/docs#118: [v0.5.1] add influxdb, update refers to v0.5.1 and fix some problems
 - [ ] dojot/docs#112, linked issues dojot/dojot#1761: Update documentation with improvements
 - [ ] dojot/docs#113, linked issues dojot/dojot#1761: [v0.5.0] release notes
 - [ ] dojot/docs#108: Adding videos
 - [ ] dojot/docs#109, linked issues dojot/dojot#1826: installation guide update
 - [ ] dojot/docs#106: Dashboard
 - [ ] dojot/docs#105: Update installation guide
 - [ ] dojot/docs#101, linked issues #100 dojot/dojot#1584: [v0.5.0] Change timestamp text to the appropriate document
 - [ ] dojot/docs#100, linked issues dojot/dojot#1584: [v0.5.0] Timestamp in payload
 - [ ] dojot/docs#90, linked issues dojot/dojot#1473: [release] kafka-ws documentation update
 - [ ] dojot/docs#99, linked issues dojot/dojot#1584 dojot/dojot#1473: [v0.5.0] Remove references to removed Auth and Device Manager readthedocs pages
 - [ ] dojot/docs#96, linked issues dojot/dojot#1726 dojot/dojot#1473: Review internal communication and iotagent arch
 - [ ] dojot/docs#95: [v0.5.0] Add poedit as a tool in the README
 - [ ] dojot/docs#91, linked issues dojot/dojot#1473: certificate and history
 - [ ] dojot/docs#92, linked issues dojot/dojot#1473: Review: faq, concepts and iotagent arch
 - [ ] dojot/docs#93, linked issues dojot/dojot#1473: [v0.5.0] Remove Device Manager readthedocs references
 - [ ] dojot/docs#89, linked issues dojot/dojot#1473: Add using mqtts with vernemq and others refs to vernemq
 - [ ] dojot/docs#88, linked issues dojot/dojot#1473: [v0.5.0] Add Locust tutorial
 - [ ] dojot/docs#86, linked issues dojot/dojot#1473: add Kafka2ftp service and node 
 - [ ] dojot/docs#85, linked issues dojot/dojot#1473: Documentation of kafka-ws intercommunication
 - [ ] dojot/docs#84, linked issues dojot/dojot#1473: x509-idenity-mgmt component documentation
 - [ ] dojot/docs#83, linked issues dojot/dojot#1473: [v0.5.0] Update tutorials to VerneMQ
 - [ ] dojot/docs#82: [v0.5.0] Add pipenv

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#218, linked issues dojot/dojot#1958: [dev] fix: Removes verification that it is onboarded and changes to maximum attempts
 - [ ] dojot/docker-compose#216: Improve influx retention comments 
 - [ ] dojot/docker-compose#214: [development] vernemq default configuration update
 - [ ] dojot/docker-compose#212: [development] license update
 - [ ] dojot/docker-compose#208: [dev] influx docker log file cycle 
 - [ ] dojot/docker-compose#204, linked issues dojot/dojot#1900 dojot/dojot#1879: [dev] change env name to kafka2ftp
 - [ ] dojot/docker-compose#201, linked issues dojot/dojot#1819 dojot/dojot#1858 dojot/dojot#1883: [dev] add influxdb, retriever and storer
 - [ ] dojot/docker-compose#206, linked issues dojot/dojot#1868: [dev] Update docker log file cycle
 - [ ] dojot/docker-compose#198: [developement] Kafka ws env vars update
 - [ ] dojot/docker-compose#199, linked issues dojot/dojot#1733: Update K2V env vars
 - [ ] dojot/docker-compose#196: add health check for mongo
 - [ ] dojot/docker-compose#195: Update V2K env vars
 - [ ] dojot/docker-compose#194, linked issues dojot/dojot#1780: set log file size for some services
 - [ ] dojot/docker-compose#191: chore: add open gui-v2
 - [ ] dojot/docker-compose#190, linked issues dojot/dojot#1722: [dev] update docker-compose file version to 3.8
 - [ ] dojot/docker-compose#188: [dev] apigw restart: always
 - [ ] dojot/docker-compose#185: Update dev branch
 - [ ] dojot/docker-compose#181: doc: comment to disable insecure mode without TLS.
 - [ ] dojot/docker-compose#180: chore: change to alpha4,add gui-v2 and kafka2ftp
 - [ ] dojot/docker-compose#178, linked issues dojot/dojot#1648: fix: add missing http port for leshan [v0.5.0]
 - [ ] dojot/docker-compose#179, linked issues dojot/dojot#1648: fix: add missing http port for leshan [dev]
 - [ ] dojot/docker-compose#175, linked issues dojot/dojot#1631: Changing Kafka's image to stay the same on kubernetes
 - [ ] dojot/docker-compose#171: Update development branch
 - [ ] dojot/docker-compose#173, linked issues dojot/dojot#1585 dojot/dojot#1484: fix kafka hostname (branch "development")
 - [ ] dojot/docker-compose#172, linked issues dojot/dojot#1585 dojot/dojot#1484: fix kafka hostname
 - [ ] dojot/docker-compose#169, linked issues dojot/dojot#1605 dojot/dojot#1604: chore: change mosca to use x509-identity-m
 - [ ] dojot/docker-compose#170, linked issues dojot/dojot#1585 dojot/dojot#1484: Fix in MqTT service volumes
 - [ ] dojot/docker-compose#157: Inclusion of new iotagent-mqtt and its peripherals
 - [ ] dojot/docker-compose#168: merge branch "release/v0.5.0" into "development"
 - [ ] dojot/docker-compose#167: Defining tag v0.5.0-alpha.3 for docker images
 - [ ] dojot/docker-compose#166, linked issues dojot/dojot#1585 dojot/dojot#1484: fix zookeeper volumes (v0.5.0)
 - [ ] dojot/docker-compose#161: chore: set timeout for kafka-ws
 - [ ] dojot/docker-compose#159, linked issues dojot/dojot#1388: chore: add auth for  /graphql route and add new route /graphql-auth 
 - [ ] dojot/docker-compose#155, linked issues dojot/dojot#1388 #36 #611 #99: chore: add auth for  /graphql route and add new route /graphql-auth [development]
 - [ ] dojot/docker-compose#156, linked issues dojot/dojot#1469 dojot/dojot#1459 dojot/dojot#1484: Inclusion of the x509-identity-mgmt and kafka-ws components
 - [ ] dojot/docker-compose#153, linked issues dojot/dojot#1414 #151: chore: https example
 - [ ] dojot/docker-compose#151, linked issues dojot/dojot#1437 #17: chore: upgrade to kong 2.0.3
 - [ ] dojot/docker-compose#148: bugfix in certificate renewal

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#105: Kafka-ws fix readness and liveness prove
 - [ ] dojot/ansible-dojot#106, linked issues dojot/dojot#1898: [k8s] Fixing docker version in the k8s playbook
 - [ ] dojot/ansible-dojot#96: [development] vernemq default configuration update
 - [ ] dojot/ansible-dojot#98: Improve comments for influxdb retention
 - [ ] dojot/ansible-dojot#94, linked issues dojot/dojot#1879: Changed license from GPL-v3 to Apache
 - [ ] dojot/ansible-dojot#91: [dev] metrics deploy order
 - [ ] dojot/ansible-dojot#86, linked issues dojot/dojot#1900 dojot/dojot#1879: [dev] change env name to kafka2ftp 
 - [ ] dojot/ansible-dojot#83, linked issues dojot/dojot#1883: [dev] add influxdb, storer and retriever
 - [ ] dojot/ansible-dojot#84, linked issues dojot/dojot#1893 dojot/dojot#1879:  [dev] Remove unused service for latency 
 - [ ] dojot/ansible-dojot#76, linked issues dojot/dojot#1848: [v2k] Add probes
 - [ ] dojot/ansible-dojot#80, linked issues dojot/dojot#1849: [k2v] Add probes
 - [ ] dojot/ansible-dojot#78, linked issues dojot/dojot#1854: docker log file size
 - [ ] dojot/ansible-dojot#74: [development] Kafka WS env vars update
 - [ ] dojot/ansible-dojot#73, linked issues dojot/dojot#1735: Standardize ansible variables
 - [ ] dojot/ansible-dojot#72: Modify V2K environment variables
 - [ ] dojot/ansible-dojot#71, linked issues dojot/dojot#1770: Changing apiGroups
 - [ ] dojot/ansible-dojot#69: chore: change to public img for gui-v2
 - [ ] dojot/ansible-dojot#67, linked issues dojot/dojot#1741: Changing rule for flowbroker
 - [ ] dojot/ansible-dojot#66: [v0.5.0] Add utility scripts
 - [ ] dojot/ansible-dojot#63, linked issues dojot/dojot#1680: NodePort 1883 will not be mapped if insecure mode is disabled
 - [ ] dojot/ansible-dojot#62: zookeeper node affinity label
 - [ ] dojot/ansible-dojot#60: create v0.5.0-alpha.4
 - [ ] dojot/ansible-dojot#61: Correct identation
 - [ ] dojot/ansible-dojot#59, linked issues dojot/dojot#1600: nginx version and update cache
 - [ ] dojot/ansible-dojot#55, linked issues dojot/dojot#1604: Allow choosing VerneMQ, Mosca or LWM2M on dojot deploy
 - [ ] dojot/ansible-dojot#52, linked issues dojot/dojot#1626: [feature] Add Locust Exporter
 - [ ] dojot/ansible-dojot#57, linked issues dojot/dojot#1600 dojot/dojot#1591: Replacement of HAProxy by NGINX
 - [ ] dojot/ansible-dojot#56, linked issues dojot/dojot#1615 dojot/dojot#1603: GUI V2 deployment
 - [ ] dojot/ansible-dojot#51: [enhance] Parameterize Node Affinity
 - [ ] dojot/ansible-dojot#49: Add TLS configurations to Kafka WS and Kong

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.6.0-rc.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.6.0-rc.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.6.0-rc.1
----
