### ISSUE TITLE
Backlog for pre-release v0.6.0-rc.2

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#2039]
Backlog
---------------------

### API Documentations:

https://dojot.github.io/auth/apiary_v0.6.0-rc.2.html
https://dojot.github.io/history/apiary_v0.6.0-rc.2.html
https://dojot.github.io/device-manager/apiary_v0.6.0-rc.2.html
https://dojot.github.io/image-manager/apiary_v0.6.0-rc.2.html
https://dojot.github.io/flowbroker/apiary_v0.6.0-rc.2.html
https://dojot.github.io/data-broker/apiary_v0.6.0-rc.2.html
https://dojot.github.io/data-manager/apiary_v0.6.0-rc.2.html
https://dojot.github.io/cron/apiary_v0.6.0-rc.2.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.6.0-rc.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.6.0-rc.2.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.6.0-rc.2

dojot/gui
---------

 - [x] dojot/gui#729, linked issues dojot/dojot#1995: [fix] Using same websocket instance for Map component
 - [x] dojot/gui#730, linked issues dojot/dojot#2005: [fix] Legends are showing 'undefined' for X-axis on details

dojot/dojot
-----------

 - [x] dojot/dojot#2026, linked issues #2007: kafka ws fixes (gracefull shutdown and healthcheck improvements)

dojot/gui-v2
------------

 - [x] dojot/gui-v2#51, linked issues dojot/dojot#1996: [feat] Updating login errors
 - [x] dojot/gui-v2#44, linked issues dojot/dojot#2006: fix: Fixed the map filter
 - [x] dojot/gui-v2#45, linked issues dojot/dojot#2015 dojot/dojot#2016: fix: Fixed selectable disabled checkbox
 - [x] dojot/gui-v2#48, linked issues dojot/dojot#2011: fix: correct handling of the attribute
 - [x] dojot/gui-v2#49, linked issues dojot/dojot#2003: fix: Logout in case of invalid token

dojot/ansible-dojot
------------------------

 - [x] dojot/ansible-dojot#113: Fixing nginx syntax error 

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.6.0-rc.2
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.6.0-rc.2
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.6.0-rc.2
----
