### ISSUE TITLE
Backlog for pre-release v0.6.0-rc.3

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2076]
Backlog
---------------------

### API Documentations:

https://dojot.github.io/auth/apiary_v0.6.0-rc.3.html
https://dojot.github.io/history/apiary_v0.6.0-rc.3.html
https://dojot.github.io/device-manager/apiary_v0.6.0-rc.3.html
https://dojot.github.io/image-manager/apiary_v0.6.0-rc.3.html
https://dojot.github.io/flowbroker/apiary_v0.6.0-rc.3.html
https://dojot.github.io/data-broker/apiary_v0.6.0-rc.3.html
https://dojot.github.io/data-manager/apiary_v0.6.0-rc.3.html
https://dojot.github.io/cron/apiary_v0.6.0-rc.3.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.6.0-rc.3.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.6.0-rc.3.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.6.0-rc.3

dojot/gui
---------

 - [x] dojot/gui#738, linked issues dojot/dojot#2068: fix: Handling appropriately with the selected device attribute
 - [x] dojot/gui#734, linked issues dojot/dojot#2068: fix: Fixes in the mini map view

dojot/backstage
---------------

 - [x] dojot/backstage#85: Adding an additional type of spelling for boolean
 - [x] dojot/backstage#83, linked issues dojot/dojot#2046: fix: Set default value for the lastN parameter

dojot/dojot
-----------

 - [x] dojot/dojot#2055, linked issues #2045: [v0.6.0][kafka-ws] improved redis retry strategy
 - [x] dojot/dojot#2047, linked issues #2017: [v.0.6.0] fixed v2k behavior on healthiness status

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#223: bump to v0.6.0-rc.1

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#113: Fixing nginx syntax error
 - [x] dojot/ansible-dojot#108: bump to v0.6.0-rc.1

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.6.0-rc.3
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.6.0-rc.3
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.6.0-rc.3
----
