### ISSUE TITLE
Backlog for pre-release v0.6.0-rc.4

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2101]
API Documentations:
https://dojot.github.io/auth/apiary_v0.6.0-rc.4.html
https://dojot.github.io/history/apiary_v0.6.0-rc.4.html
https://dojot.github.io/device-manager/apiary_v0.6.0-rc.4.html
https://dojot.github.io/image-manager/apiary_v0.6.0-rc.4.html
https://dojot.github.io/flowbroker/apiary_v0.6.0-rc.4.html
https://dojot.github.io/data-broker/apiary_v0.6.0-rc.4.html
https://dojot.github.io/data-manager/apiary_v0.6.0-rc.4.html
https://dojot.github.io/cron/apiary_v0.6.0-rc.4.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.6.0-rc.4.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.6.0-rc.4.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.6.0-rc.4

dojot/gui
---------

 - [ ] dojot/gui#747, linked issues dojot/dojot#2069: [feat] - Extends leafmap with socket to be used in device's map

dojot/dojot
-----------

 - [ ] dojot/dojot#2089, linked issues #2081 #2073 #2094: [kafka-ws] [v0.6.0] fix: add reconnect in client of redis expiration connection and shutdown if exceed client redis reconnection attempts
 - [ ] dojot/dojot#2091, linked issues dojot/dojot#2083: [rel/v0.6.0] Correction of EJBCA script
 - [ ] dojot/dojot#2079, linked issues: [v0.6.0] Remove github token usage in kafka-ws actions and update action version

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#64, linked issues dojot/dojot#2082: Adding NOTICE file for license exceptions

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#231: Update dojot version to v0.6.0-rc.4

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#118: Update dojot version to v0.6.0-rc.4
 
 ----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.6.0-rc.4
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.6.0-rc.4
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.6.0-rc.4
----
