### ISSUE TITLE
Backlog for release v0.6.0

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2121]
Read The docs 
---------------------

https://dojotdocs.readthedocs.io/en/v0.6.0/
https://dojotdocs.readthedocs.io/pt_BR/v0.6.0/

### API Documentations:

https://dojot.github.io/auth/apiary_v0.6.0.html
https://dojot.github.io/history/apiary_v0.6.0.html
https://dojot.github.io/device-manager/apiary_v0.6.0.html
https://dojot.github.io/image-manager/apiary_v0.6.0.html
https://dojot.github.io/flowbroker/apiary_v0.6.0.html
https://dojot.github.io/data-broker/apiary_v0.6.0.html
https://dojot.github.io/data-manager/apiary_v0.6.0.html
https://dojot.github.io/cron/apiary_v0.6.0.html
https://dojot.github.io/dojot/x509-identity-mgmt/apiary_v0.6.0.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.6.0.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.6.0

### Full Backlog:

dojot/gui
---------

 - [ ] dojot/gui#746, linked issues dojot/dojot#2082: Adding NOTICE file for license exceptions
 - [x] dojot/gui#747, linked issues dojot/dojot#2069: [feat] - Extends leafmap with socket to be used in device's map
 - [x] dojot/gui#738, linked issues dojot/dojot#2068: fix: Handling appropriately with the selected device attribute
 - [x] dojot/gui#734, linked issues dojot/dojot#2068: fix: Fixes in the mini map view
 - [x] dojot/gui#729, linked issues dojot/dojot#1995: [fix] Using same websocket instance for Map component
 - [x] dojot/gui#730, linked issues dojot/dojot#2005: [fix] Legends are showing 'undefined' for X-axis on details

dojot/backstage
---------------

 - [x] dojot/backstage#85: Adding an additional type of spelling for boolean
 - [x] dojot/backstage#83, linked issues dojot/dojot#2046: fix: Set default value for the lastN parameter

dojot/dojot
-----------

 - [x] dojot/dojot#2089, linked issues #2081 #2073 #2094: [kafka-ws] [v0.6.0] fix: add reconnect in client of redis expiration connection and shutdown if exceed client redis reconnection attempts
 - [x] dojot/dojot#2091, linked issues dojot/dojot#2083: [rel/v0.6.0] Correction of EJBCA script
 - [ ] dojot/dojot#2079, linked issues: [v0.6.0] Remove github token usage in kafka-ws actions and update action version
 - [x] dojot/dojot#2055, linked issues #2045: [v0.6.0][kafka-ws] improved redis retry strategy
 - [x] dojot/dojot#2047, linked issues #2017: [v.0.6.0] fixed v2k behavior on healthiness status
 - [x] dojot/dojot#2026, linked issues #2007: [v0.6.0] kafka ws fixes (gracefull shutdown and healthcheck improvements)

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#64, linked issues dojot/dojot#2082: Adding NOTICE file for license exceptions
 - [x] dojot/gui-v2#51, linked issues dojot/dojot#1996: [feat] Updating login errors
 - [x] dojot/gui-v2#44, linked issues dojot/dojot#2006: fix: Fixed the map filter
 - [x] dojot/gui-v2#45, linked issues dojot/dojot#2015 dojot/dojot#2016: fix: Fixed selectable disabled checkbox
 - [x] dojot/gui-v2#48, linked issues dojot/dojot#2011: fix: correct handling of the attribute
 - [x] dojot/gui-v2#49, linked issues dojot/dojot#2003: fix: Logout in case of invalid token

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#231: Update dojot version to v0.6.0-rc.4
 - [x] dojot/docker-compose#228: Update dojot version to v0.6.0-rc.3
 - [x] dojot/docker-compose#223: bump to v0.6.0-rc.1

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#118: Update dojot version to v0.6.0-rc.4
 - [x] dojot/ansible-dojot#116: Update dojot version to v0.6.0-rc.3
 - [x] dojot/ansible-dojot#113: Fixing nginx syntax error
 - [x] dojot/ansible-dojot#108: bump to v0.6.0-rc.1

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.6.0
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.6.0
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.6.0
----
