### ISSUE TITLE
Backlog for pre-release v0.7.0-rc.1

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2156]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.7.0-rc.1.html
https://dojot.github.io/history/apiary_v0.7.0-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.7.0-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.7.0-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.7.0-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.7.0-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.7.0-rc.1.html
https://dojot.github.io/cron/apiary_v0.7.0-rc.1.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.0-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.0-rc.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.0-rc.1

dojot/cron
----------

 - [x] dojot/cron#36, linked issues dojot/dojot#1766: Fixed api blueprint example
 - [x] dojot/cron#35, linked issues dojot/dojot#1988: Fixed cron time validation
 - [x] dojot/cron#34: This change overwrites the timestamp and tenant for broker events

dojot/gui
---------

 - [x] dojot/gui#755, linked issues dojot/dojot#2152: [dev] Generate Certificate - add association
 - [x] dojot/gui#750, linked issues dojot/dojot#2071: [fix] Updating i18n component
 - [x] dojot/gui#739, linked issues dojot/dojot#2069: [feat] - Extends leafmap with socket to be used in device's map
 - [ ] dojot/gui#749, linked issues dojot/dojot#2100: Adding NOTICE file for license exceptions
 - [x] dojot/gui#733, linked issues dojot/dojot#2068: fix: Fixes in the mini map view
 - [x] dojot/gui#726, linked issues dojot/dojot#1995: [fix]  Using same websocket instance for Map component 
 - [x] dojot/gui#724, linked issues dojot/dojot#2005 dojot/dojot#2005: [fix] Legends are showing 'undefined' for X-axis on details

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#341, linked issues dojot/dojot#1978 dojot/dojot#1298: Fixing set value for binary option in FTP topic node and an initial value has been defined for the httpRequest variable on the http node

dojot/backstage
---------------

 - [x] dojot/backstage#95, linked issues dojot/dojot#2096: fix: Correct handling for truly Boolean values
 - [x] dojot/backstage#89, linked issues dojot/dojot#1982: Removed the widget identification from the OperationType attribute
 - [x] dojot/backstage#84, linked issues dojot/dojot#1982: Feat: Changes for better widget support with template
 - [x] dojot/backstage#86: Adding an additional type of spelling for boolean
 - [x] dojot/backstage#78, linked issues dojot/dojot#1981: Dash template

dojot/dojot
-----------

 - [x] dojot/dojot#2151, linked issues #2152: certreq: add belongs update
 - [x] dojot/dojot#2135, linked issues dojot/dojot#1939: [certificate-acl] Added an http endpoint to get an acl entry
 - [x] dojot/dojot#2128: Fixed healthcheck in the Dockerfile for k2v service
 - [x] dojot/dojot#2127: Fixed healthcheck in the Dockerfile for v2k service
 - [x] dojot/dojot#2132: [certificate-acl] Rename the acl docker image
 - [x] dojot/dojot#2090, linked issues dojot/dojot#2082: Adding NOTICE file for license exceptions
 - [x] dojot/dojot#2093, linked issues dojot/dojot#2082: [kafka-ws] Adding NOTICE file for license exceptions
 - [x] dojot/dojot#2119, linked issues dojot/dojot#1939: [x509-identity-mgmt] Internal endpoint for querying certificates
 - [x] dojot/dojot#2107, linked issues: [kakfa-ws] Fix: Dockerfile Healthcheck
 - [x] dojot/dojot#2066, linked issues: [feat][development] added certificate acl service
 - [ ] dojot/dojot#2103, linked issues #2036: [locust] Github actions - breaking when build docker image 
 - [x] dojot/dojot#2097, linked issues #2081 #2073 #2094: [kafka-ws] [dev] fix: add reconnect in client of redis expiration connection and shutdown if exceed client redis reconnection attempt
 - [ ] dojot/dojot#2080, linked issues: [dev] Remove github token usage in kafka-ws actions and update action version
 - [ ] dojot/dojot#1983, linked issues dojot/dojot#1994: [feat] adds History Proxy service
 - [ ] dojot/dojot#2067, linked issues: [feat][development] vernemq certificate acl integration
 - [x] dojot/dojot#2074, linked issues: [x509-identity-mgmt] Fix device-id length schema
 - [ ] dojot/dojot#2072, linked issues dojot/dojot#1940: [cert-sidecar] Increasing the request cert timeout
 - [ ] dojot/dojot#2064, linked issues dojot/dojot#1540: [x509-identity-mgmt] Parameterization of the list of application names for certificates (belongsTo.application)
 - [ ] dojot/dojot#2065, linked issues dojot/dojot##1940: [cert-sidecar] Configuration parameter changed (Name of the application in which the sidecar will be associated)
 - [ ] dojot/dojot#2061, linked issues: [cert-sidecar] documentation improvement
 - [ ] dojot/dojot#2060, linked issues dojot/dojot#1940: [cert-sidecar] Payload to associate certificate with the application (belongsTo)
 - [ ] dojot/dojot#2058, linked issues: [cert-sidecar] fix: cron expression
 - [x] dojot/dojot#2056, linked issues #2045: [dev][kafka-ws] improved redis retry strategy
 - [ ] dojot/dojot#2052, linked issues dojot/dojot#1940: [x509-identity-mgmt] Support for content negotiation on internal endpoints
 - [ ] dojot/dojot#2050, linked issues dojot/dojot#1940: [cert-sidecar] Obtaining the CA bundle file
 - [x] dojot/dojot#2048, linked issues #2017: [development] fixed v2k behavior on healthiness status
 - [ ] dojot/dojot#2029, linked issues: [cert-sidecar] Update README with informations about serve.setSecureContext in node.js
 - [ ] dojot/dojot#2044, linked issues dojot/dojot#1540: Flag-enabled SubjectDN and DeviceExists validations
 - [x] dojot/dojot#2040, linked issues #2007: [development] kafka ws fixes (gracefull shutdown and healthcheck improvements)
 - [ ] dojot/dojot#2037, linked issues dojot/dojot#2031: [x509-identity-mgmt] Internal endpoint to retrieve the trusted CAs bundle
 - [ ] dojot/dojot#1993, linked issues #1629 #222: [verne,k2v,v2k] Remove scripts tls to use cert-sidecar 
 - [ ] dojot/dojot#2022, linked issues dojot/dojot#1943: [x509-identity-mgmt] Notification of events on Kafka
 - [x] dojot/dojot#1980, linked issues dojot/dojot#1942: [x509-identity-mgmt] Device validation when associating with certificate

dojot/gui-v2
------------

 - [x] dojot/gui-v2#69, linked issues dojot/dojot#2096: Better manipulation of Boolean value in the table widget
 - [x] dojot/gui-v2#67, linked issues dojot/dojot#2098: Editing multiple devices
 - [x] dojot/gui-v2#66, linked issues dojot/dojot#2051: fix: Widget organization
 - [x] dojot/gui-v2#65, linked issues dojot/dojot#2099: fix: Tooltip text
 - [x] dojot/gui-v2#62, linked issues dojot/dojot#1982: feat: Widget with template
 - [x] dojot/gui-v2#63, linked issues dojot/dojot#2082: Adding NOTICE file for license exceptions
 - [x] dojot/gui-v2#42, linked issues dojot/dojot#1996: [feat] Updating login errors
 - [x] dojot/gui-v2#43, linked issues dojot/dojot#2006: fix: Fixed the map filter
 - [x] dojot/gui-v2#44, linked issues dojot/dojot#2006: fix: Fixed the map filter
 - [x] dojot/gui-v2#45, linked issues dojot/dojot#2015 dojot/dojot#2016: fix: Fixed selectable disabled checkbox
 - [x] dojot/gui-v2#46, linked issues dojot/dojot#2015 dojot/dojot#2016: fix: Fixed selectable disabled checkbox
 - [x] dojot/gui-v2#47, linked issues dojot/dojot#2011: fix: correct handling of the attribute
 - [x] dojot/gui-v2#48, linked issues dojot/dojot#2011: fix: correct handling of the attribute
 - [x] dojot/gui-v2#49, linked issues dojot/dojot#2003: fix: Logout in case of invalid token
 - [x] dojot/gui-v2#50, linked issues dojot/dojot#2003: fix: Logout in case of invalid token

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#238, linked issues dojot/dojot#2124: Remove redis acl to use certificate acl with http in iotagent-mqtt
 - [x] dojot/docker-compose#232: fix: rabbitmq healthcheck
 - [ ] dojot/docker-compose#234, linked issues dojot/dojot#2092: note: secret kafka-ws
 - [x] dojot/docker-compose#237, linked issues dojot/dojot#1939: Added the certificate-acl service to the docker-compose file
 - [x] dojot/docker-compose#233: note about mosca with tls
 - [ ] dojot/docker-compose#230, linked issues dojot/dojot#1956: Delete docs directory
 - [ ] dojot/docker-compose#227, linked issues dojot/dojot#1540 dojot/dojot#1940: Update VerneMQ config file (in Base64)
 - [x] dojot/docker-compose#226, linked issues dojot/dojot#2004: Fix error when restart flowbroker
 - [ ] dojot/docker-compose#225: [docker-compose] x509-identity-mgmt and cert-sidecar configuration fixes
 - [ ] dojot/docker-compose#224: [docker-compose] some configuration fixes
 - [ ] dojot/docker-compose#222, linked issues dojot/dojot#1629 dojot/dojot#1993: add sidecar to verne, v2k, k2v
 - [x] dojot/docker-compose#220, linked issues dojot/dojot#1964: Separation of the EJBCA from the x509-identity-mgmt

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#124, linked issues dojot/dojot#2124: Create Certificate ACL deployment - Ansible
 - [ ] dojot/ansible-dojot#125, linked issues dojot/dojot#2092: note: secret kafka-ws
 - [x] dojot/ansible-dojot#120, linked issues dojot/dojot#2062: [dev] Implement log file rotation
 - [ ] dojot/ansible-dojot#117, linked issues dojot/dojot#1802: add vernemq sidecar
 - [x] dojot/ansible-dojot#114, linked issues dojot/dojot#1964 #220: Separation of EJBCA from x509-identity-mgmt and volume sharing
 - [x] dojot/ansible-dojot#110, linked issues dojot/dojot#1851: [Ansible] Automation of Volumes in the k8s environment
 - [x] dojot/ansible-dojot#112, linked issues dojot/dojot#1908: Upgrade k8s version to 1.19.8
 - [x] dojot/ansible-dojot#109, linked issues dojot/dojot#1851: [Ansible] Automation of Labels in the k8s environment
 - [x] dojot/ansible-dojot#107, linked issues dojot/dojot#1991: [Ansible] Chose the IotAgent to be deployed in services.yaml file

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.0-rc.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.0-rc.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.0-rc.1
----
