### ISSUE TITLE
Backlog for pre-release v0.7.0-rc.2

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2198]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.7.0-rc.2.html
https://dojot.github.io/history/apiary_v0.7.0-rc.2.html
https://dojot.github.io/device-manager/apiary_v0.7.0-rc.2.html
https://dojot.github.io/image-manager/apiary_v0.7.0-rc.2.html
https://dojot.github.io/flowbroker/apiary_v0.7.0-rc.2.html
https://dojot.github.io/data-broker/apiary_v0.7.0-rc.2.html
https://dojot.github.io/data-manager/apiary_v0.7.0-rc.2.html
https://dojot.github.io/cron/apiary_v0.7.0-rc.2.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.0-rc.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.0-rc.2.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.0-rc.2

dojot/history
-------------

 - [x] dojot/history#121, linked issues dojot/dojot#2167: feat: receive timestamp range for search and change data return limit

dojot/gui
---------

 - [x] dojot/gui#757, linked issues dojot/dojot#2131 dojot/dojot#1815: [fix] Fixing the firmware update button

dojot/dojot
-----------

 - [x] dojot/dojot#2181, linked issues #2169: [VerneMQ] Added some patches to allow to refresh the ca trust-store

dojot/docs
----------

 - [x] dojot/docs#137: Remove old video, add some notes and the new domain variable in docker-compose 
 - [x] dojot/docs#133, linked issues dojot/dojot#2126 dojot/dojot#2134 dojot/dojot#2153 dojot/dojot#2143: Changes to v0.7.0 and some improvements

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#242: [v0.7] exposing some variables and add some healthchecks

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#128, linked issues dojot/dojot#2172: [v0.7.0] Fix dojot volumes syntax

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.0-rc.2
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.0-rc.2
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.0-rc.2
----
