### ISSUE TITLE
Backlog for pre-release v0.7.0-rc.3

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2215]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.7.0-rc.3.html
https://dojot.github.io/history/apiary_v0.7.0-rc.3.html
https://dojot.github.io/device-manager/apiary_v0.7.0-rc.3.html
https://dojot.github.io/image-manager/apiary_v0.7.0-rc.3.html
https://dojot.github.io/flowbroker/apiary_v0.7.0-rc.3.html
https://dojot.github.io/data-broker/apiary_v0.7.0-rc.3.html
https://dojot.github.io/data-manager/apiary_v0.7.0-rc.3.html
https://dojot.github.io/cron/apiary_v0.7.0-rc.3.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.0-rc.3.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.0-rc.3.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.0-rc.3

dojot/history
-------------

 - [ ] dojot/history#122, linked issues dojot/dojot#2205: feat: get all notifications if filter parameters are passed

dojot/dojot
-----------

 - [ ] dojot/dojot#2194: [Locust] fix locust's dockerfile and improve generate_certs to associate a device with a certificate
 - [ ] dojot/dojot#2207, linked issues #2196: [VERNEMQ] Exposed the port 9883 in the VerneMQ container

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#246, linked issues dojot/dojot#2196: [VERNEMQ] Changed the configuration to add an extra ssl listener

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#133, linked issues dojot/dojot#2196: [VERNEMQ] Changed the configuration to add an extra ssl listener
 - [ ] dojot/ansible-dojot#130: Add 100k tag to InfluxDB and Certificate ACL

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.0-rc.3
----
----

Locust available at https://github.com/dojot/docker-compose-locust/releases/tag/v0.7.0-rc.3
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.0-rc.3
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.0-rc.3
----
