### ISSUE TITLE
Backlog for release v0.7.0

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2272]
Read The docs 
---------------------

https://dojotdocs.readthedocs.io/en/v0.7.0/
https://dojotdocs.readthedocs.io/pt_BR/v0.7.0/

### API Documentations:

https://dojot.github.io/auth/apiary_v0.7.0.html
https://dojot.github.io/history/apiary_v0.7.0.html
https://dojot.github.io/device-manager/apiary_v0.7.0.html
https://dojot.github.io/image-manager/apiary_v0.7.0.html
https://dojot.github.io/flowbroker/apiary_v0.7.0.html
https://dojot.github.io/data-broker/apiary_v0.7.0.html
https://dojot.github.io/data-manager/apiary_v0.7.0.html
https://dojot.github.io/cron/apiary_v0.7.0.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.0.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.0.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.0

### Full Backlog:

dojot/history
-------------
 - [x] dojot/history#125, linked issues dojot/dojot#2234: docs: Updated history apiary including new parameters for notifications
 - [x] dojot/history#122, linked issues dojot/dojot#2205: feat: get all notifications if filter parameters are passed
 - [x] dojot/history#121, linked issues dojot/dojot#2167: feat: receive timestamp range for search and change data return limit

dojot/gui
---------

 - [x] dojot/gui#757, linked issues dojot/dojot#2131 dojot/dojot#1815: [fix] Fixing the firmware update button

dojot/dojot
-----------

 - [x] dojot/dojot#2257: Merge branch 'hotfix/2186' into 'release/v0.7.0'
 - [x] dojot/dojot#2254, linked issues #2186: Refactored the process of including a timestamp
 - [ ] dojot/dojot#2237: remove npm-debug.log file
 - [ ] dojot/dojot#2214: Hotfix/2186
 - [x] dojot/dojot#2194: [Locust] fix locust's dockerfile and improve generate_certs to associate a device with a certificate
 - [x] dojot/dojot#2207, linked issues #2196: [VERNEMQ] Exposed the port 9883 in the VerneMQ container
 - [x] dojot/dojot#2181, linked issues #2169: [VerneMQ] Added some patches to allow to refresh the ca trust-store

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#262: Bump to v0.7.0
 - [ ] dojot/docker-compose#260: Bump to v0.7.0-rc.4
 - [ ] dojot/docker-compose#247: bump to v0.7.0-rc.3
 - [x] dojot/docker-compose#246, linked issues dojot/dojot#2196: [VERNEMQ] Changed the configuration to add an extra ssl listener
 - [ ] dojot/docker-compose#245: Bump to v0.7.0-rc.2
 - [x] dojot/docker-compose#242: [v0.7] exposing some variables and add some healthchecks

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#142: Bump to v0.7.0
 - [ ] dojot/ansible-dojot#141: Bump to v0.7.0-rc.4
 - [ ] dojot/ansible-dojot#134: bump to v0.7.0-rc.3
 - [x] dojot/ansible-dojot#133, linked issues dojot/dojot#2196: [VERNEMQ] Changed the configuration to add an extra ssl listener
 - [ ] dojot/ansible-dojot#132: Bump to v0.7.0-rc.2
 - [x] dojot/ansible-dojot#130: Add 100k tag to InfluxDB and Certificate ACL
 - [x] dojot/ansible-dojot#128, linked issues dojot/dojot#2172: [v0.7.0] Fix dojot volumes syntax
 
 ----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.0
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.0
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.0
----
