### ISSUE TITLE
Backlog for pre-release v0.7.1-rc.1

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2291]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.7.1-rc.1.html
https://dojot.github.io/history/apiary_v0.7.1-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.7.1-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.7.1-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.7.1-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.7.1-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.7.1-rc.1.html
https://dojot.github.io/cron/apiary_v0.7.1-rc.1.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.1-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.1-rc.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.1-rc.1

dojot/history
-------------

 - [x] dojot/history#124, linked issues dojot/dojot#2182: [Dev] Update: split persister's requirements
 - [x] dojot/history#125, linked issues dojot/dojot#2234: docs: Updated history apiary including new parameters for notifications
 - [x] dojot/history#126, linked issues dojot/dojot#2269: FIx TTL error
 - [x] dojot/history#123, linked issues dojot/dojot#2182: [Dev] [History] Get History in CSV format #2182
 - [x] dojot/history#122, linked issues dojot/dojot#2205: feat: get all notifications if filter parameters are passed
 - [x] dojot/history#118, linked issues dojot/dojot#2116 dojot/dojot#2116: behavior modification history and persister
 - [x] dojot/history#121, linked issues dojot/dojot#2167: feat: receive timestamp range for search and change data return limit
 -  dojot/history#114, linked issues dojot/dojot#1986: Add Feature/keycloak branch to development branch (not to test)

dojot/cron
----------

 - [x] dojot/cron#49, linked issues dojot/dojot#2032 dojot/dojot#2033 dojot/dojot#2034 dojot/dojot#2078 dojot/dojot#2095: Enhancement of the cron service and use of the SDK library (test funcionality and exception situations)

dojot/gui
---------

 - dojot/gui#771: [fix] Updating license exceptions (not to test)
 - dojot/gui#769: [Fix] Updating lock files (not to test)
 - [x] dojot/gui#760, linked issues #2225: Adding download csv for reports
 - [x] dojot/gui#759, linked issues dojot/dojot#1230 dojot/dojot#1230: translation of a name field in templates module filters
  - [x] dojot/gui#758, linked issues dojot/dojot#2131 dojot/dojot#1815: [fix] Fixing the firmware update button

dojot/device-manager
--------------------

 - [x] dojot/device-manager#187, linked issues dojot/dojot#1498 dojot/dojot#1498: correcting error in the readme writing of the word "crypto"

dojot/flowbroker
----------------

 - [ ] dojot/flowbroker#356: Add basic-authenticantion header
 - [x] dojot/flowbroker#368: Add feature reconnect to RabbitMQ
 - [x] dojot/flowbroker#361, linked issues dojot/dojot#2164: [Dev] [FlowBroker] Feat: Add in node "switch" the option to compare 2 values in 'msg'

dojot/dojot
-----------

 - [x] dojot/dojot#2254, linked issues #2186: Refactored the process of including a timestamp
 - [x] dojot/dojot#2209, linked issues dojot/dojot#2183: [Dev] [Retriever/InfluxDB] Get data in CSV format
 -  dojot/dojot#2248, linked issues #2247: fix: correction of environment variables
 -  dojot/dojot#2171, linked issues dojot/dojot#2141: Creating an endpoint to be used with Graphql
 - [x] dojot/dojot#2231, linked issues #2192: feat: new http agent for communication with dojot
 - dojot/dojot#2237: remove npm-debug.log file
 - [x] dojot/dojot#2214: Hotfix/2186
 - dojot/dojot#2194: [Locust] fix locust's dockerfile and improve generate_certs to associate a device with a certificate
 -  dojot/dojot#2207, linked issues #2196: [VERNEMQ] Exposed the port 9883 in the VerneMQ container
 -  dojot/dojot#2170, linked issues dojot/dojot#1986: Change key generation method to self-signed
 - [x] dojot/dojot#2180, linked issues #2169: [VerneMQ] Added some patches to allow to refresh the ca trust-store
 - [x] dojot/dojot#2181, linked issues #2169: [VerneMQ] Added some patches to allow to refresh the ca trust-store

dojot/gui-v2
------------

 - [x] dojot/gui-v2#74, linked issues dojot/dojot#2224: feat: Added export of widgets data in csv
 - [x] dojot/gui-v2#75, linked issues dojot/dojot#2184: fix: Updated markers and added missing colors
 - [x] dojot/gui-v2#76, linked issues dojot/dojot#2154: fix: Clear form state when device or template is changed

dojot/docs
----------

 - [x] dojot/docs#139: Update Dojot-Installation-Guide
 - [x] dojot/docs#137: Remove old video, add some notes and the new domain variable in docker-compose 
 - [x] dojot/docs#133, linked issues dojot/dojot#2126 dojot/dojot#2134 dojot/dojot#2153 dojot/dojot#2143: Changes to v0.7.0 and some improvements

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#266, linked issues dojot/dojot#2240: [Dev] Adding InfluxDB to the monitoring service
 - [x] dojot/docker-compose#265, linked issues dojot/dojot#2241: [Dev] Adding MongoDB to the monitoring service
 - [x] dojot/docker-compose#264, linked issues dojot/dojot#2204: [Dev] Adding Kong to the monitoring service
 - [x] dojot/docker-compose#261, linked issues dojot/dojot#2203: [Dev] Adding Kafka to the monitoring service
 - [x] dojot/docker-compose#259, linked issues dojot/dojot#2202: [Dev] Adding VerneMQ to the monitoring service
 -  dojot/docker-compose#258: Fix v2k image tag
 - dojot/docker-compose#253, linked issues dojot/dojot#2201: [Dev] Adding prometheus and grafana as a service
 -  dojot/docker-compose#254, linked issues dojot/dojot#2246: Add HTTP Agent deployment
 - [x] dojot/docker-compose#251: Add memory limit to mongodb
 -  dojot/docker-compose#246, linked issues dojot/dojot#2196: [VERNEMQ] Changed the configuration to add an extra ssl listener
 - [x] dojot/docker-compose#244: [dev] exposing some variables and add some healthchecks 

dojot/ansible-dojot (devops team tests)
-------------------

 - [dojot/ansible-dojot#139, linked issues dojot/dojot#2246: Add HTTP Agent deployment - Ansible
 - [x] dojot/ansible-dojot#129, linked issues dojot/dojot#1918: Changed the Kubernetes Container Runtime to containerd
 - dojot/ansible-dojot#133, linked issues dojot/dojot#2196: [VERNEMQ] Changed the configuration to add an extra ssl listener
 - dojot/ansible-dojot#131: [Dev] Add 100k tag to InfluxDB and Certificate ACL
 - dojot/ansible-dojot#127, linked issues dojot/dojot#2172: [Dev] Fix dojot volumes syntax
 
 
----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.1-rc.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.1-rc.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.1-rc.1
----
