### ISSUE TITLE
Backlog for pre-release v0.7.1-rc.2

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2383]
Backlog:
API Documentations:

https://dojot.github.io/auth/apiary_v0.7.1-rc.2.html
https://dojot.github.io/history/apiary_v0.7.1-rc.2.html
https://dojot.github.io/device-manager/apiary_v0.7.1-rc.2.html
https://dojot.github.io/image-manager/apiary_v0.7.1-rc.2.html
https://dojot.github.io/flowbroker/apiary_v0.7.1-rc.2.html
https://dojot.github.io/data-broker/apiary_v0.7.1-rc.2.html
https://dojot.github.io/data-manager/apiary_v0.7.1-rc.2.html
https://dojot.github.io/cron/apiary_v0.7.1-rc.2.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.1-rc.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.1-rc.2.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.1-rc.2

dojot/history
-------------
 - [x] dojot/history#134, linked issues dojot/dojot#2339: [0.7.1] [History] Fix: docs

dojot/cron
----------
 - [x] dojot/cron#55: fix: startup
 - [x] dojot/cron#54, linked issues dojot/dojot#2325: fix: internal error creating a cron job

dojot/auth
----------
 - [x] dojot/auth#127: #2268

dojot/flowbroker
----------------
 - [x] dojot/flowbroker#375, linked issues dojot/dojot#2185: Change file encoding to option box

dojot/dojot
-----------
 - [x] dojot/dojot#2379: fix: device data message generation
 - [x] dojot/dojot#2367, linked issues #2353: fix: error message with a wrong parameter
 - [x] dojot/dojot#2360, linked issues #2319 #2305 #2306 #2315:  fix: util timestamp and response status codes

dojot/ansible-dojot
-------------------
 - [x] dojot/ansible-dojot#149, linked issues dojot/dojot#2233: Fix default lwm2m ports
 - [x] dojot/ansible-dojot#147: Fix Cron consumer and producer bug

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.1-rc.2
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.1-rc.2
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.1-rc.2
----
