### ISSUE TITLE
Backlog for pre-release v0.7.1-rc.3

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2463]
Backlog:
API Documentations:

https://dojot.github.io/auth/apiary_v0.7.1-rc.3.html
https://dojot.github.io/history/apiary_v0.7.1-rc.3.html
https://dojot.github.io/device-manager/apiary_v0.7.1-rc.3.html
https://dojot.github.io/image-manager/apiary_v0.7.1-rc.3.html
https://dojot.github.io/flowbroker/apiary_v0.7.1-rc.3.html
https://dojot.github.io/data-broker/apiary_v0.7.1-rc.3.html
https://dojot.github.io/data-manager/apiary_v0.7.1-rc.3.html
https://dojot.github.io/cron/apiary_v0.7.1-rc.3.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.1-rc.3.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.1-rc.3.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.1-rc.3

dojot/gui
---------

 - [x] dojot/gui#773, linked issues dojot/dojot#2335: Fix: Issue 2335 - Report generate: initial period is always AM

dojot/dojot
-----------

 - [x] dojot/dojot#2420, linked issues #2415: fix: timestamp error catch in create-many
 - [x] dojot/dojot#2435, linked issues #2318 #2426: FIx reload certificate with external ca

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#282: [docker-compose] Deployment - Update HTTP Agent

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#160: [ansible] Deployment - Update HTTP Agent
 - [x] dojot/ansible-dojot#157, linked issues dojot/dojot#2324: Change certificate acl label to dojot
 
----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.1-rc.3
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.1-rc.3
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.1-rc.3
----
