### ISSUE TITLE
Backlog for release v0.7.1

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2482]
Read The docs 
---------------------

https://dojotdocs.readthedocs.io/en/v0.7.1/
https://dojotdocs.readthedocs.io/pt_BR/v0.7.1/

### API Documentations:

https://dojot.github.io/auth/apiary_v0.7.1.html
https://dojot.github.io/history/apiary_v0.7.1.html
https://dojot.github.io/device-manager/apiary_v0.7.1.html
https://dojot.github.io/image-manager/apiary_v0.7.1.html
https://dojot.github.io/flowbroker/apiary_v0.7.1.html
https://dojot.github.io/data-broker/apiary_v0.7.1.html
https://dojot.github.io/data-manager/apiary_v0.7.1.html
https://dojot.github.io/cron/apiary_v0.7.1.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.7.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.7.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.7.1

### Full Backlog:

dojot/history
-------------

 - [x] dojot/history#134, linked issues dojot/dojot#2339: [0.7.1] [History] Fix: docs

dojot/cron
----------

 - [x] dojot/cron#55: fix: startup
 - [x] dojot/cron#54, linked issues dojot/dojot#2325: fix: internal error creating a cron job

dojot/gui
---------

 - [x] dojot/gui#773, linked issues dojot/dojot#2335: Fix: Issue 2335 - Report generate: initial period is always AM

dojot/auth
----------

 - [x] dojot/auth#127: #2268

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#375, linked issues dojot/dojot#2185: Change file encoding to option box

dojot/dojot
-----------

 - [x] dojot/dojot#2471: [HTTP-AGENT] Hotfixes - External Certificates
 - [x] dojot/dojot#2420, linked issues #2415: fix: timestamp error catch in create-many
 - [x] dojot/dojot#2435, linked issues #2318 #2426: FIx reload certificate with external ca
 - [ ] dojot/dojot#2379: fix: device data message generation
 - [x] dojot/dojot#2367, linked issues #2353: fix: error message with a wrong parameter
 - [x] dojot/dojot#2360, linked issues #2319 #2305 #2306 #2315:  fix: util timestamp and response status codes

dojot/gui-v2
------------

 - [x] dojot/gui-v2#109: updated node version

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#282: [docker-compose] Deployment - Update HTTP Agent

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#160: [ansible] Deployment - Update HTTP Agent
 - [x] dojot/ansible-dojot#157, linked issues dojot/dojot#2324: Change certificate acl label to dojot
 - [x] dojot/ansible-dojot#149, linked issues dojot/dojot#2233: Fix default lwm2m ports
 - [x] dojot/ansible-dojot#147: Fix Cron consumer and producer bug
 
----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.7.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.7.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.7.1
----
