### ISSUE TITLE
Backlog for pre-release v0.8.0-rc.1

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2530]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.8.0-rc.1.html
https://dojot.github.io/history/apiary_v0.8.0-rc.1.html
https://dojot.github.io/device-manager/apiary_v0.8.0-rc.1.html
https://dojot.github.io/image-manager/apiary_v0.8.0-rc.1.html
https://dojot.github.io/flowbroker/apiary_v0.8.0-rc.1.html
https://dojot.github.io/data-broker/apiary_v0.8.0-rc.1.html
https://dojot.github.io/data-manager/apiary_v0.8.0-rc.1.html
https://dojot.github.io/cron/apiary_v0.8.0-rc.1.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.8.0-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.8.0-rc.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0-rc.1

dojot/history
-------------
 - [ ] dojot/history#134, linked issues dojot/dojot#2339: [0.7.1] [History] Fix: docs
 - [ ] dojot/history#133, linked issues dojot/dojot#2259: MongoDB - Allow changing data expiration time

dojot/cron
----------
 - [ ] dojot/cron#55: fix: startup
 - [ ] dojot/cron#54, linked issues dojot/dojot#2325: fix: internal error creating a cron job

dojot/gui
---------
 - [ ] dojot/gui#773, linked issues dojot/dojot#2335: Fix: Issue 2335 - Report generate: initial period is always AM
 - [ ] dojot/gui#772, linked issues dojot/dojot#2340: Fix: Issue #2340 - Device creation - Passing ID to backend wrongly
 - [ ] dojot/gui#768: Issue 1782

dojot/device-manager
--------------------
 - [ ] dojot/device-manager#193: [DOJOT-14] Update: Allow register specific identification (ID) for one device

dojot/auth
----------
 - [ ] dojot/auth#127: #2268

dojot/flowbroker
----------------
 - [ ] dojot/flowbroker#375, linked issues dojot/dojot#2185: Change file encoding to option box
 - [ ] dojot/flowbroker#374, linked issues dojot/dojot#2294: Fix log error without stringify
 - [ ] dojot/flowbroker#372, linked issues dojot/dojot#2222: Fix return when get error

dojot/backstage
---------------
 - [ ] dojot/backstage#128: Fix Actions
 - [ ] dojot/backstage#122, linked issues dojot/dojot#2427: Imp: Updated libraries
 - [ ] dojot/backstage#121, linked issues dojot/dojot#2433: Nx Feature - 2433 - Show Associated Certificate
 - [ ] dojot/backstage#119: Refactor/mutation certificate csr
 - [ ] dojot/backstage#118: Feature: Mutations for create certificate with CSR and register external certificate
 - [ ] dojot/backstage#117, linked issues dojot/dojot#2399: security flow in device creation
 - [ ] dojot/backstage#116, linked issues dojot/dojot#2373: Feature - CA Queries Mutations
 - [ ] dojot/backstage#115, linked issues dojot/dojot#2372: Feature - Security Queries Mutations
 - [ ] dojot/backstage#114, linked issues dojot/dojot#2375: feat: Certificate Creation
 - [ ] dojot/backstage#113, linked issues dojot/dojot#2333: Feature - Templates Queries and Mutations
 - [ ] dojot/backstage#112, linked issues dojot/dojot#2332: Fix - Create Device Mutation
 - [ ] dojot/backstage#110: Fix getTemplates Query Returned Fields
 - [ ] dojot/backstage#111, linked issues dojot/dojot#2332: Feature - Edit Device Mutation
 - [ ] dojot/backstage#109, linked issues dojot/dojot#2303: feat: Added certificate listing
 - [ ] dojot/backstage#107, linked issues dojot/dojot#2358: Improved getDeviceById query
 - [ ] dojot/backstage#108, linked issues dojot/dojot#2366: Feature - Delete Multiple Devices
 - [ ] dojot/backstage#106, linked issues dojot/dojot#2331 dojot/dojot#2301 dojot/dojot#2342: Backstage Refactor

dojot/dojot
-----------
 - [ ] dojot/dojot#2528: [VerneMQ] Deprecate unencrypted git protocol use
 - [ ] dojot/dojot#2504: [Cert-sidecar] cron expiration is true by default
 - [ ] dojot/dojot#2520: [ file-mgmt ] - GitHub Actions - GH Pages
 - [ ] dojot/dojot#2478: [locust] fix locust initialization
 - [ ] dojot/dojot#2516: [file-mgmt] fix: secrets loader
 - [ ] dojot/dojot#2493, linked issues #2371: [Certificate-acl] correlation id functionality was added
 - [ ] dojot/dojot#2471: [HTTP-AGENT] Hotfixes - External Certificates
 - [ ] dojot/dojot#2470: [influxdb-retriever] Fix: synchronization with device-manager 
 - [ ] dojot/dojot#2420, linked issues #2415: fix: timestamp error catch in create-many
 - [ ] dojot/dojot#2435, linked issues #2318 #2426: FIx reload certificate with external ca
 - [ ] dojot/dojot#2425, linked issues #2424: fix initialization: add support to redis 6.2.6
 - [ ] dojot/dojot#2351, linked issues #2347: [Dev] [influxbd-retriever] ILPF generic route
 - [ ] dojot/dojot#2376, linked issues #2318: refactor: example and error message
 - [ ] dojot/dojot#2385: dojot/dojot#2380 | dojot/dojot#2381 - Add certificates filter using k…
 - [ ] dojot/dojot#2379: fix: device data message generation
 - [ ] dojot/dojot#2362, linked issues #2348: Feature: Correlation id received must be passed on in other communications
 - [ ] dojot/dojot#2367, linked issues #2353: fix: error message with a wrong parameter
 - [ ] dojot/dojot#2365: Action device basic
 - [ ] dojot/dojot#2360, linked issues #2319 #2305 #2306 #2315:  fix: util timestamp and response status codes
 - [ ] dojot/dojot#2344: feat: authentication and device authorization service by user and password
 - [ ] dojot/dojot#2350: Action filemgmt
 - [ ] dojot/dojot#2341: [ file-mgmt ] - GitHub Actions
 - [ ] dojot/dojot#2322: [DOJOT-8] [DOJOT-9] [DOJOT-11] Object storage and retrieval
 - [ ] dojot/dojot#2288, linked issues dojot/dojot#1907: Issue 1907
 - [ ] dojot/dojot#2266: [Locust] fix some issues

dojot/gui-v2
------------
 - [ ] dojot/gui-v2#109: updated node version
 - [ ] dojot/gui-v2#108: updated node version
 - [ ] dojot/gui-v2#77, linked issues dojot/dojot#2165: feat: Added a confirmation modal for widget deletion

dojot/docker-compose
--------------------
 - [ ] dojot/docker-compose#292: update network configuration and log file-mgmt and minio-files
 - [ ] dojot/docker-compose#291: [DEV] Fix: minio first bucket creation
 - [ ] dojot/docker-compose#288: Created Minio secrets file
 - [ ] dojot/docker-compose#282: [docker-compose] Deployment - Update HTTP Agent
 - [ ] dojot/docker-compose#280, linked issues dojot/dojot#2401: Update grafana
 - [ ] dojot/docker-compose#279, linked issues dojot/dojot#2386: [docker-compose] Interface WEB InfluxDB
 - [ ] dojot/docker-compose#275, linked issues dojot/dojot#1483: Feature/loki
 - [ ] dojot/docker-compose#276: Feature: Add global correlation-id plugin
 - [ ] dojot/docker-compose#277, linked issues dojot/dojot#2370: [Docker-compose] Deployment - Include Device-basic-auth and  http-agent-redis
 - [ ] dojot/docker-compose#274: [Docker-Compose] file-mgmt deploy
 - [ ] dojot/docker-compose#273, linked issues #98: [Fix] Port grafana
 - [ ] dojot/docker-compose#272: [Dev] Removing externalization of ports 
 - [ ] dojot/docker-compose#271, linked issues #2162: docker-compose: All secrets must always be different
 - [ ] dojot/docker-compose#270: [Fix] Readme and data source prometheus
 - [ ] dojot/docker-compose#269: [Fix] Overview and kong json in monitoring service

dojot/ansible-dojot
-------------------
 - [ ] dojot/ansible-dojot#170: [ansible] deploy file-mgmt
 - [ ] dojot/ansible-dojot#169: Prometheus helm
 - [ ] dojot/ansible-dojot#166, linked issues dojot/dojot#2338: [ansible] Distributed volumes
 - [ ] dojot/ansible-dojot#165: Monitoring helm
 - [ ] dojot/ansible-dojot#159, linked issues dojot/dojot#2227: [velero] add kubernetes disaster recovery feature
 - [ ] dojot/ansible-dojot#158: Loki volume adjustments and code quality improvements for tasks and playbooks
 - [ ] dojot/ansible-dojot#160: [ansible] Deployment - Update HTTP Agent
 - [ ] dojot/ansible-dojot#157, linked issues dojot/dojot#2324: Change certificate acl label to dojot
 - [ ] dojot/ansible-dojot#156, linked issues dojot/dojot#1483: feature/loki
 - [ ] dojot/ansible-dojot#155, linked issues dojot/dojot#2387: [ansible-dojot] Interface WEB InfluxDB and HTTP-Agent Redis
 - [ ] dojot/ansible-dojot#153: Feature: add global correlation-id plugin
 - [ ] dojot/ansible-dojot#152, linked issues dojot/dojot#2321: [ansible] HTTPS in the NGINX
 - [ ] dojot/ansible-dojot#151, linked issues dojot/dojot#2270: [Fix] Storage Retention and PVC prometheus
 - [ ] dojot/ansible-dojot#150, linked issues dojot/dojot#2307: [ansible][secrets] All secrets must always be different
 - [ ] dojot/ansible-dojot#149, linked issues dojot/dojot#2233: Fix default lwm2m ports
 - [ ] dojot/ansible-dojot#145, linked issues dojot/dojot#2163: Install dojot using EKS (Amazon Cloud)
 - [ ] dojot/ansible-dojot#147: Fix Cron consumer and producer bug

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.8.0-rc.1
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.8.0-rc.1
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.8.0-rc.1
----
