### ISSUE TITLE
Backlog for pre-release v0.8.0-rc.2

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2576]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.8.0-rc.2.html
https://dojot.github.io/history/apiary_v0.8.0-rc.2.html
https://dojot.github.io/device-manager/apiary_v0.8.0-rc.2.html
https://dojot.github.io/image-manager/apiary_v0.8.0-rc.2.html
https://dojot.github.io/flowbroker/apiary_v0.8.0-rc.2.html
https://dojot.github.io/data-broker/apiary_v0.8.0-rc.2.html
https://dojot.github.io/data-manager/apiary_v0.8.0-rc.2.html
https://dojot.github.io/cron/apiary_v0.8.0-rc.2.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.8.0-rc.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.8.0-rc.2.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0-rc.2
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v0.8.0-rc.2

dojot/gui
---------
 - [ ] dojot/gui#781, linked issues dojot/dojot#2532: adjust device id to null

dojot/flowbroker
----------------
 - [ ] dojot/flowbroker#394: Reconnection to RabbitMQ
 - [ ] dojot/flowbroker#390: Reconnection to RabbitMQ

dojot/dojot
-----------
 - [ ] dojot/dojot#2564: [DOJOT-7] Fixes for 0.8.0
 - [ ] dojot/dojot#2562, linked issues #2533: [certificate-acl] Correction of dependency injection into the interce…

dojot/ansible-dojot
-------------------
 - [ ] dojot/ansible-dojot#182: Including job rabbitmq
 - [ ] dojot/ansible-dojot#181: Including postgres exporter
 - [ ] dojot/ansible-dojot#179: Merge branch 'development' into release/v0.8.0
 - [ ] dojot/ansible-dojot#177:  K3s para ambientes on-premises

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.8.0-rc.2
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.8.0-rc.2
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.8.0-rc.2
----
