### ISSUE TITLE
Backlog for pre-release v0.8.0-rc.3

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2601]
### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.8.0-rc.3.html
https://dojot.github.io/history/apiary_v0.8.0-rc.3.html
https://dojot.github.io/device-manager/apiary_v0.8.0-rc.3.html
https://dojot.github.io/image-manager/apiary_v0.8.0-rc.3.html
https://dojot.github.io/flowbroker/apiary_v0.8.0-rc.3.html
https://dojot.github.io/data-broker/apiary_v0.8.0-rc.3.html
https://dojot.github.io/data-manager/apiary_v0.8.0-rc.3.html
https://dojot.github.io/cron/apiary_v0.8.0-rc.3.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.8.0-rc.3.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.8.0-rc.3.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0-rc.3
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v0.8.0-rc.3

dojot/gui
---------

 - [ ] dojot/gui#785, linked issues dojot/dojot#2540: Feat/device id creation

dojot/dojot
-----------

 - [ ] dojot/dojot#2587: [Http-agent] Record expiration updates in redis
 - [ ] dojot/dojot#2584: [Http-agent] Message validations must follow the architecture schema
 - [ ] dojot/dojot#2583: [influxdb-retriever] Fix: return ACK on ignored payloads and kafka group id configuration
 - [ ] dojot/dojot#2579: [Device-basic-authentication] Devices can have only one credential saved
 - [ ] dojot/dojot#2582: [DOJOT-7] Fixes for 0.8.0-rc1

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#179, linked issues dojot/dojot#2580 dojot/dojot#2581: Fix: Issue 2580 - Problems for select attributes when create a widget

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#301: [DOJOT-36] Fix: bucket creation job
 - [ ] dojot/docker-compose#297: flexibility of services at startup

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#200: add metrics server k8s
 - [ ] dojot/ansible-dojot#198: Separate dojot_version into dojot_backend_version and dojot_frontend_version 
 - [ ] dojot/ansible-dojot#196: add vars hpa keda
 - [ ] dojot/ansible-dojot#194: Ansible enhancement
 - [ ] dojot/ansible-dojot#191: add helm install
 - [ ] dojot/ansible-dojot#189: add autoscaling using keda for vernemq, k2v and v2k services
 - [ ] dojot/ansible-dojot#187: Fix influxdb-retriever connection with kafka-server
 - [ ] dojot/ansible-dojot#186: Including secrets in grafana
 - [ ] dojot/ansible-dojot#183: Separation of the deployment from the monitoring solution

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.8.0-rc.3
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.8.0-rc.3
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.8.0-rc.3
----
