### ISSUE TITLE
Backlog for pre-release v0.8.0-rc.5

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2616]
### Versions:
Backend: v0.8.0-rc.4
Frontend: v0.8.0-rc.4

### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.8.0-rc.4.html
https://dojot.github.io/history/apiary_v0.8.0-rc.4.html
https://dojot.github.io/device-manager/apiary_v0.8.0-rc.4.html
https://dojot.github.io/image-manager/apiary_v0.8.0-rc.4.html
https://dojot.github.io/flowbroker/apiary_v0.8.0-rc.4.html
https://dojot.github.io/data-broker/apiary_v0.8.0-rc.4.html
https://dojot.github.io/data-manager/apiary_v0.8.0-rc.4.html
https://dojot.github.io/cron/apiary_v0.8.0-rc.4.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.8.0-rc.4.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.8.0-rc.4.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0-rc.4
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v0.8.0-rc.4

dojot/dojot
-----------

 - [x] dojot/dojot#2615: [DOJOT-41] Fix: Adjusting settings to decrease timeout logs while writing.
 - [x] dojot/dojot#2610: [DOJOT-41] Fix: Adjusting settings to decrease timeout logs while writing.
 - [x] dojot/dojot#2604: [Http-agent] Added insecure mode via parameters
 

dojot/docker-compose
--------------------

 - [x] dojot/docker-compose#304: Include basic auth deploy

dojot/ansible-dojot
-------------------

 - [x] dojot/ansible-dojot#207: Include basic auth deploy
 - [ ] dojot/ansible-dojot#201: Fixing monitoring service

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.8.0-rc.5
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.8.0-rc.5
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.8.0-rc.5
----

[DOJOT-41]: https://dojot.atlassian.net/browse/DOJOT-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-41]: https://dojot.atlassian.net/browse/DOJOT-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
