### ISSUE TITLE
Backlog for pre-release v0.8.0-rc.6

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2632]
### Versions:
Backend: v0.8.0-rc.5
Frontend: v0.8.0-rc.4

### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.8.0-rc.5.html
https://dojot.github.io/history/apiary_v0.8.0-rc.5.html
https://dojot.github.io/device-manager/apiary_v0.8.0-rc.5.html
https://dojot.github.io/image-manager/apiary_v0.8.0-rc.5.html
https://dojot.github.io/flowbroker/apiary_v0.8.0-rc.5.html
https://dojot.github.io/data-broker/apiary_v0.8.0-rc.5.html
https://dojot.github.io/data-manager/apiary_v0.8.0-rc.5.html
https://dojot.github.io/cron/apiary_v0.8.0-rc.5.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.8.0-rc.5.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.8.0-rc.5.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0-rc.5
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v0.8.0-rc.5

dojot/flowbroker
----------------

 - [ ] dojot/flowbroker#400, linked issues dojot/dojot#2577: correction in instantiation order

dojot/dojot
-----------

 - [ ] dojot/dojot#2623: [DOJOT-49] fix: Catching uncaught exception so the service doesn't get unhealthy.
 

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#311: [DEVOPS-383] add route insecure http-agent
 - [ ] dojot/docker-compose#309: Remove old services and add development profile
 - [ ] dojot/docker-compose#307: Add basic-auth to kong

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#215: [DEVOPS-383] add route insecure http-agent
 - [ ] dojot/ansible-dojot#214: Add basic-auth to kong
 - [ ] dojot/ansible-dojot#212: Add undeploy.yaml playbook
 - [ ] dojot/ansible-dojot#211: Add keda as an optional service
 - [ ] dojot/ansible-dojot#210: Fixing monitoring service

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.8.0-rc.6
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.8.0-rc.6
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.8.0-rc.6
----
