### ISSUE TITLE
Backlog for pre-release v0.8.0-rc.7

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2640]
### Versions:
Backend: v0.8.0-rc.6
Frontend: v0.8.0-rc.4

### Backlog:

API Documentations:

https://dojot.github.io/auth/apiary_v0.8.0-rc.6.html
https://dojot.github.io/history/apiary_v0.8.0-rc.6.html
https://dojot.github.io/device-manager/apiary_v0.8.0-rc.6.html
https://dojot.github.io/image-manager/apiary_v0.8.0-rc.6.html
https://dojot.github.io/flowbroker/apiary_v0.8.0-rc.6.html
https://dojot.github.io/data-broker/apiary_v0.8.0-rc.6.html
https://dojot.github.io/data-manager/apiary_v0.8.0-rc.6.html
https://dojot.github.io/cron/apiary_v0.8.0-rc.6.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v0.8.0-rc.6.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v0.8.0-rc.6.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v0.8.0-rc.6
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v0.8.0-rc.6

dojot/flowbroker
----------------

 - [ ] dojot/flowbroker#404, linked issues dojot/dojot#2577: promise return correction

dojot/dojot
-----------

 - [ ] dojot/dojot#2635: [Http-agent] http only mode must not depend on https

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#315: Create tools profile
 - [ ] dojot/docker-compose#314: [DEVOPS-435] Docker-compose - Self Signed Certificate Nginx

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#219: Fix requirements.txt
 - [ ] dojot/ansible-dojot#218: Documentation update
 - [ ] dojot/ansible-dojot#217: [DEVOPS-435] Kubernetes - Self Signed Certificate Nginx

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v0.8.0-rc.7
----
----

Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v0.8.0-rc.7
----
----

Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v0.8.0-rc.7
----
