### ISSUE TITLE
Backlog for pre-release dev-alpha.1

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2686]
### Backlog:

dojot/cron
----------

 - [ ] dojot/cron#70: Merge Development from Feature/keycloak v2
 - [ ] dojot/cron#68, linked issues dojot/dojot#2569: Fix: Dockerfile
 - [ ] dojot/cron#66: Add keycloak features

dojot/device-manager
--------------------

 - [ ] dojot/device-manager#204: adjust date format
 - [ ] dojot/device-manager#203: log format update
 - [ ] dojot/device-manager#200: [DOJOT-96] Feature - Sorting
 - [ ] dojot/device-manager#201: [DOJOT-75] [DOJOT-76] Feature - Unique Labels
 - [ ] dojot/device-manager#198, linked issues #2419: [Device_manager] Fix: correção do filtro
 - [ ] dojot/device-manager#199: [DOJOT-95] Update: device-manager configure topic
 - [ ] dojot/device-manager#197, linked issues dojot/dojot#2569: Remove: data-broker dependency

dojot/flowbroker
----------------

 - [ ] dojot/flowbroker#402: [DOJOT-95] Update: actuation topic
 - [ ] dojot/flowbroker#390: Reconnection to RabbitMQ

dojot/data-manager
------------------

 - [ ] dojot/data-manager#52: adjust version and setSid

dojot/dojot
-----------

 - [ ] dojot/dojot#2685: Adjust keycloak actions
 - [ ] dojot/dojot#2682: Fix: development branch
 - [ ] dojot/dojot#2680: update version 
 - [ ] dojot/dojot#2664: [file-mgmt] [http-agent] [device-basic-auth] Update node and sdkversion
 - [ ] dojot/dojot#2661: Fix development with keycloak
 - [ ] dojot/dojot#2636, linked issues dojot/dojot#2522: [certificate-acl] Fix Cascading failure generated by certificate-acl
 - [ ] dojot/dojot#2651: [DOJOT-128] Make accessing Influxdb data more flexible.
 - [ ] dojot/dojot#2647: Adds settings using environment variables
 - [ ] dojot/dojot#2637: [DOJOT-86] Fix: Implementing validations when authorization.mode=cn
 - [ ] dojot/dojot#2630: [DOJOT-96] Feature - Sorting
 - [ ] dojot/dojot#2646: Merge development from feature/keycloak-v2 
 - [ ] dojot/dojot#2645: Fix: merge pr #2639 issues
 - [ ] dojot/dojot#2643: Fix infludb retriever
 - [ ] dojot/dojot#2639: Merge feature/keycloak-v2 from release/0.8.0 and development
 - [ ] dojot/dojot#2633: Merge branch 'release/v0.8.0' into development
 - [ ] dojot/dojot#2635: [Http-agent] http only mode must not depend on https
 - [ ] dojot/dojot#2623: [DOJOT-49] fix: Catching uncaught exception so the service doesn't get unhealthy.
 - [ ] dojot/dojot#2626: [DOJOT-95] [k2v-bridge] Update: change device-manager.device topic to device-manager.configure
 - [ ] dojot/dojot#2618, linked issues dojot/dojot#2569: Add fixes and updates in some services
 - [ ] dojot/dojot#2621: [DEVOPS-273] [influxdb-retriever] Fix: uuid sub-library
 
dojot/backstage
---------------

 - [ ] dojot/backstage#149: Actions in batch
 - [ ] dojot/backstage#148: Feature - Actions in Batch
 - [ ] dojot/backstage#147: Feature - Keycloak V2
 - [ ] dojot/backstage#145: [DOJOT-96] Feature - Sorting
 - [ ] dojot/backstage#146: [DOJOT-75] [DOJOT-76] Feature - Unique Labels 
 - [ ] dojot/backstage#143: [DOJOT-77] Return Created Date
 - [ ] dojot/backstage#144: Fix: License Exceptions
 - [ ] dojot/backstage#142: [DOJOT-70] - Feature: Certificate and keys as zip file to download
 - [ ] dojot/backstage#140, linked issues #6015 #5995 #5990 #6015 #6015 #6015: Bump moment from 2.29.1 to 2.29.4
 - [ ] dojot/backstage#141, linked issues dojot/dojot#2588: Fix: Issue 2588 - When accessing the Dashboard tosts are being displayed on the screen.
 - [ ] dojot/backstage#139, linked issues dojot/dojot#2569: Feature - Support Multiple DBs
 - [ ] dojot/backstage#133, linked issues dojot/dojot#2412: Feat: Favorite Devices
 - [ ] dojot/backstage#138: Fix - Security Service Import
 - [ ] dojot/backstage#125, linked issues dojot/dojot#2494: Issue#2494: disassociate device on delete
 - [ ] dojot/backstage#136: Fix private key header
 - [ ] dojot/backstage#137, linked issues dojot/dojot#2543: feat: insert device id

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#225: FIX: Change in production webpack configuration
 - [ ] dojot/gui-v2#224: [DOJOT-57] [Feature] - Associating devices with certificates in batch
 - [ ] dojot/gui-v2#223: [DOJOT-56] [Feature] - Import Certificates in Batch
 - [ ] dojot/gui-v2#222: [DOJOT-55] - Create devices with CSV
 - [ ] dojot/gui-v2#220: [Actions in Batch] - Delete devices and templates in batch
 - [ ] dojot/gui-v2#221: [DOJOT-50] - Create devices in batch
 - [ ] dojot/gui-v2#203: [DOJOT-96] Feature - Sorting
 - [ ] dojot/gui-v2#208: [DOJOT-75] [DOJOT-76] Feature - Unique Labels
 - [ ] dojot/gui-v2#205: [DOJOT-83] - Accessibility improvements for the dark theme
 - [ ] dojot/gui-v2#207: [DOJOT-84] - New Menu
 - [ ] dojot/gui-v2#206: [DOJOT-68] - Change position of Wizards Steppers
 - [ ] dojot/gui-v2#204: [DOJOT-74] - add info tooltips and attribute label validation to template creation
 - [ ] dojot/gui-v2#202: [DOJOT-80] - Dashboard: Widget Creation - name and description
 - [ ] dojot/gui-v2#201: [DOJOT-82] - Light theme accessibility improvements
 - [ ] dojot/gui-v2#199: [DOJOT-77] Add "New" Chip When Create Something
 - [ ] dojot/gui-v2#200: [DOJOT-79] Use a Different Color For Each Attr
 - [ ] dojot/gui-v2#195: [DOJOT 73] - Fix Device Creation and Dashboard Responsiveness
 - [ ] dojot/gui-v2#196: [DOJOT-70] - Feature: Certificate and keys as zip file to download
 - [ ] dojot/gui-v2#188: [DOJOT-71] Fix - Change Finish Button Text
 - [ ] dojot/gui-v2#189: [DOJOT-66] Fix - Name Column Before ID Column
 - [ ] dojot/gui-v2#190: [DOJOT-72] Fix - Remove All history.goBack to Prevent Returning to Home
 - [ ] dojot/gui-v2#193: [DOJOT-78] Replace "widget" by "panel" in Translations
 - [ ] dojot/gui-v2#198, linked issues dojot/dojot#2619: Fix - GUI NX CI
 - [ ] dojot/gui-v2#197: Feature - Crete Build Scripts
 - [ ] dojot/gui-v2#180, linked issues dojot/dojot#2586: Feature - Integrate GUI NX MFE with Keycloak
 - [ ] dojot/gui-v2#192: [DOJOT-69] Fix: Attributes presentation in device creation
 - [ ] dojot/gui-v2#191: [DOJOT-67] Fix: Highlighting action tips in device creation wizard
 - [ ] dojot/gui-v2#184, linked issues dojot/dojot#2606: Fix 2606: Delete device error
 - [ ] dojot/gui-v2#186, linked issues dojot/dojot#2589 dojot/dojot#2603: Feature - Add a Tooltip in Icon Buttons
 - [ ] dojot/gui-v2#187, linked issues dojot/dojot#2593: Fix - Add a Text for the Default Order of Widget Filters
 - [ ] dojot/gui-v2#183, linked issues dojot/dojot#2598: 2598 - Adjust toast message for 'Use My Certificate'
 - [ ] dojot/gui-v2#185, linked issues dojot/dojot#2595: Fix - Use Certificate Success Message
 - [ ] dojot/gui-v2#182, linked issues dojot/dojot#2594: Mfe feat/favorite devices
 - [ ] dojot/gui-v2#178, linked issues dojot/dojot#2571: Fix - Change Button Variants of Certificate Creation Page
 - [ ] dojot/gui-v2#177: Feature - Add Scripts to Improve Productivity
 - [ ] dojot/gui-v2#176, linked issues dojot/dojot#2544: Fix - Show if an Input Field is Required
 - [ ] dojot/gui-v2#175, linked issues dojot/dojot#2553: [2553] Added toast to widget wizard
 - [ ] dojot/gui-v2#174: Added material-ui libraries as eager loading
 - [ ] dojot/gui-v2#172, linked issues dojot/dojot#2554: Fix - Change Button Texts and Icon
 - [ ] dojot/gui-v2#173, linked issues dojot/dojot#2567: Fix - Remove Object From Attr Values
 
 dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#325: Empty minio secrets
 - [ ] dojot/docker-compose#324: Add dev tools to docker-compose.yml
 - [ ] dojot/docker-compose#323: Fix development with keycloak
 - [ ] dojot/docker-compose#319: Merge branch 'feature/keycloak-v2' into development
 - [ ] dojot/docker-compose#318: Duplicate http agent
 - [ ] dojot/docker-compose#312: update docker-compose keycloak
 - [ ] dojot/docker-compose#308, linked issues dojot/dojot#2569: Keycloak - Remove profiles for tests
 - [ ] dojot/docker-compose#306, linked issues dojot/dojot#2569: Iam keycloack new impl
 - [ ] dojot/docker-compose#295, linked issues dojot/dojot#2408: Update:  keycloak integration with device-manager, cert-sidecar, gui-…
 - [ ] dojot/docker-compose#300: Merge branch 'release/v0.8.0' into development 
 - [ ] dojot/docker-compose#297: flexibility of services at startup
 - [ ] dojot/docker-compose#296: Bump to v0.8.0-rc.2
 
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/dev-alpha.1
----

[DOJOT-96]: https://dojot.atlassian.net/browse/DOJOT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-75]: https://dojot.atlassian.net/browse/DOJOT-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-76]: https://dojot.atlassian.net/browse/DOJOT-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-95]: https://dojot.atlassian.net/browse/DOJOT-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-95]: https://dojot.atlassian.net/browse/DOJOT-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-128]: https://dojot.atlassian.net/browse/DOJOT-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
