### ISSUE TITLE
Backlog for pre-release dev-alpha.2

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2701]
### Backlog:

API Documentations:

https://dojot.github.io/device-manager/apiary_dev-alpha.2.html
https://dojot.github.io/flowbroker/apiary_dev-alpha.2.html
https://dojot.github.io/data-manager/apiary_dev-alpha.2.html
https://dojot.github.io/cron/apiary_dev-alpha.2.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_dev-alpha.2.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_dev-alpha.2.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=dev-alpha.2
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=dev-alpha.2

dojot/backstage
---------------

 - [ ] dojot/backstage#152: Fix - Unit Tests
 - [ ] dojot/backstage#151: Destroy the session when the token is invalid
 - [ ] dojot/backstage#150: fix: Change to return influxdb history data list

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#226: redirect to login in case of 401 error
 

dojot/dojot
-----------

 - [ ] dojot/dojot#2697: [DOJOT-191] [x509-identity-mgmt] Fix: adjust solution
 - [ ] dojot/dojot#2696: [DOJOT-191] [device-basic-authentication] Fix: response with "invalid device" for all cases

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#332: Change keycloak-microservice-sidecar version
 - [ ] dojot/docker-compose#330: Fix quotations marks
 - [ ] dojot/docker-compose#329: Remove http-agent and basic-auth exposed port
 - [ ] dojot/docker-compose#328: fix to remote server

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#227: Remove old services from nginx
 - [ ] dojot/ansible-dojot#226: [Feature] Keycloak Deployment on Kubernetes
 - [ ] dojot/ansible-dojot#225: Fixing Dashboards
 - [ ] dojot/ansible-dojot#212: Add undeploy.yaml playbook
 - [ ] dojot/ansible-dojot#211: Add keda as an optional service
 - [ ] dojot/ansible-dojot#210: Fixing monitoring service
 - [ ] dojot/ansible-dojot#207: Include basic auth deploy
 - [ ] dojot/ansible-dojot#201: Fixing monitoring service
 - [ ] dojot/ansible-dojot#204: metrics server for just k8s
 - [ ] dojot/ansible-dojot#200: add metrics server k8s
 - [ ] dojot/ansible-dojot#200: add metrics server k8s
 - [ ] dojot/ansible-dojot#198: Separate dojot_version into dojot_backend_version and dojot_frontend_version 
 - [ ] dojot/ansible-dojot#196: add vars hpa keda
 - [ ] dojot/ansible-dojot#194: Ansible enhancement
 - [ ] dojot/ansible-dojot#191: add helm install
 - [ ] dojot/ansible-dojot#189: add autoscaling using keda for vernemq, k2v and v2k services
 - [ ] dojot/ansible-dojot#187: Fix influxdb-retriever connection with kafka-server
 - [ ] dojot/ansible-dojot#186: Including secrets in grafana
 - [ ] dojot/ansible-dojot#183: Separation of the deployment from the monitoring solution
 - [ ] dojot/ansible-dojot#182: Including job rabbitmq
 - [ ] dojot/ansible-dojot#181: Including postgres exporter
 - [ ] dojot/ansible-dojot#177:  K3s para ambientes on-premises
 - [ ] dojot/ansible-dojot#178: Fixing folders, CRD's and namespace dojot-monitoring
 - [ ] dojot/ansible-dojot#175: Including mongodb exporter
 - [ ] dojot/ansible-dojot#173: Including Influxdb job
 
----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/dev-alpha.2
----
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/dev-alpha.2
----
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/dev-alpha.2
----
