### ISSUE TITLE
Backlog for pre-release dev-alpha.3

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2724]
### Backlog:

API Documentations:

https://dojot.github.io/device-manager/apiary_dev-alpha.3.html
https://dojot.github.io/data-manager/apiary_dev-alpha.3.html
https://dojot.github.io/cron/apiary_dev-alpha.3.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_dev-alpha.3.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_dev-alpha.3.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=dev-alpha.3
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=dev-alpha.3
https://dojot.github.io/dojot/data-visualization/reports/report-manager/doc.html?version=dev-alpha.3

dojot/backstage
---------------

 - [ ] dojot/backstage#163: [DOJOT-52] - Feat: delete templates in batch integration
 - [ ] dojot/backstage#164: Fix - Get Devices Return
 - [ ] dojot/backstage#162: [DOJOT-207] Utiliza query unificada para tela de detalhes
 - [ ] dojot/backstage#161: Cria nova variável para habilitar a interface gráfica
 - [ ] dojot/backstage#160: Adiciona variável de ambiente para controle do nível de log
 - [ ] dojot/backstage#159: Delete Multiple Devices Integration
 - [ ] dojot/backstage#158: Update backstage Dockerfile to accept healthcheck
 - [ ] dojot/backstage#157: Actions in batch
 - [ ] dojot/backstage#156: [DOJOT-194] Feature - Actuate
 - [ ] dojot/backstage#153: [DOJOT-141] [DOJOT-143] Create device with on or off state.
 - [ ] dojot/backstage#155: [DOJOT-30] - Feature: Reports
 - [ ] dojot/backstage#154: Handling influx data recovery error in device details

dojot/gui-v2
------------

 - [x] dojot/gui-v2#251: [DOJOT-52 ] - Feat: delete templates in batch integration
 - [ ] dojot/gui-v2#250: Fix/report translations
 - [ ] dojot/gui-v2#249: fix translations on create report page
 - [ ] dojot/gui-v2#248: add missing icon
 - [ ] dojot/gui-v2#247: Fix - Webpack Production Configs
 - [ ] dojot/gui-v2#246: Delete Multiple Devices Integration
 - [ ] dojot/gui-v2#245: Refactor: adjust Create Multiple Devices
 - [ ] dojot/gui-v2#243: [DOJOT-194] Feature - Actuate
 - [ ] dojot/gui-v2#228: [DOJOT-141] [DOJOT-143] Feature - Device State
 - [ ] dojot/gui-v2#227: Feature - Reports

dojot/cron
----------

 - [x] dojot/cron#75: [DOJOT-191] Fix: request validation

dojot/device-manager
--------------------

 - [x] dojot/device-manager#206: implementa adicao de dispositivos em lote
 - [x] dojot/device-manager#205: [DOJOT-141] [DOJOT-143] Create device with on or off state.

dojot/kong
----------

 - [x] dojot/kong#33: Recupera conteúdo da imagem dojot/kong:feature-api-gateway-kong

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#407: [DOJOT-155] Flowbroker integration with keycloak
 - [ ] dojot/flowbroker#401: Release/v0.8.0
 - [x] dojot/flowbroker#403: [DOJOT-95] The actuator topic split from data topic
 - [ ] dojot/flowbroker#404, linked issues dojot/dojot#2577: promise return correction

dojot/dojot
-----------

 - [ ] dojot/dojot#2723: Corrige quebra na leitura de string pelo retriever
 - [ ] dojot/dojot#2720: Action device manager batch
 - [x] dojot/dojot#2712: [DOJOT-48] Add: Device-manager batch
 - [ ] dojot/dojot#2713: Fix - Report Manager Sonarcloud Problems
 - [x] dojot/dojot#2698: Feature - Report Manager
 - [ ] dojot/dojot#2681: [DOJOT-150] add: Grafana dashboards with InfluxDB telemetry data.
 - [x] dojot/dojot#2699: [DOJOT-144] Add: Receive measurement for device on and off.
 - [x] dojot/dojot#2707: [DOJOT-191] Fix: Http-agent ack undefined
 - [ ] dojot/dojot#2705: [DOJOT-148] Fix: repeatedly set prefix on data
 - [x] dojot/dojot#2702: [DOJOT-191] [http-agent] Fix: device identification
 - [x] dojot/dojot#2675: [DOJOT-148]  Telegraf custom for dojot
 
 
 dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#337: [DOJOT48] - Feature/dojot 48 - device manager batch - remove device and templates
 - [ ] dojot/docker-compose#343: Add Health Check to all services
 - [ ] dojot/docker-compose#341: Defined the Redis services using the anchor/alias feature of yaml
 - [ ] dojot/docker-compose#340: Altera a inicialização do banco para usar diretamente o sql
 - [ ] dojot/docker-compose#338: [DOJOT-144] Add: v2k-bridge for keycloak secret.
 - [ ] dojot/docker-compose#326: Feature - Report Manager
 - [ ] dojot/docker-compose#331: Feature/reports-nx
 - [x] dojot/docker-compose#333: Fixa uma versão antiga do pgadmin compatível com o pg 9
 - [x] dojot/docker-compose#335: [DOJOT-148] Influxdb-storer replaced by telegraf
 - [ ] dojot/docker-compose#336: [DOJOT-172] Kong Audit

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#233: update secrets in the secrets service
 - [x] dojot/ansible-dojot#234: InfluxDB Retriever HotFix
 - [x] dojot/ansible-dojot#231: Duplicate http agent
 - [ ] dojot/ansible-dojot#230: Vault
 

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/dev-alpha.3
----
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/dev-alpha.3
----
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/dev-alpha.3
----

[DOJOT-52]: https://dojot.atlassian.net/browse/DOJOT-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-207]: https://dojot.atlassian.net/browse/DOJOT-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-194]: https://dojot.atlassian.net/browse/DOJOT-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
