### ISSUE TITLE
Backlog for pre-release dev-alpha.4

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2746]
### Backlog:

API Documentations:

https://dojot.github.io/device-manager/apiary_dev-alpha.4.html
https://dojot.github.io/data-manager/apiary_dev-alpha.4.html
https://dojot.github.io/cron/apiary_dev-alpha.4.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_dev-alpha.4.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_dev-alpha.4.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=dev-alpha.4
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=dev-alpha.4
https://dojot.github.io/dojot/data-visualization/reports/report-manager/doc.html?version=dev-alpha.4

dojot/backstage
---------------

 - [ ] dojot/backstage#163: [DOJOT-52] - Feat: delete templates in batch integration
 - [ ] dojot/backstage#164: Fix - Get Devices Return
 - [ ] dojot/backstage#162: [DOJOT-207] Utiliza query unificada para tela de detalhes
 - [ ] dojot/backstage#161: Cria nova variável para habilitar a interface gráfica
 - [ ] dojot/backstage#160: Adiciona variável de ambiente para controle do nível de log
 - [ ] dojot/backstage#159: Delete Multiple Devices Integration
 - [ ] dojot/backstage#158: Update backstage Dockerfile to accept healthcheck
 - [ ] dojot/backstage#157: Actions in batch
 - [ ] dojot/backstage#156: [DOJOT-194] Feature - Actuate
 - [ ] dojot/backstage#153: [DOJOT-141] [DOJOT-143] Create device with on or off state.
 - [ ] dojot/backstage#155: [DOJOT-30] - Feature: Reports
 - [ ] dojot/backstage#154: Handling influx data recovery error in device details

dojot/backstage
---------------

 - [ ] dojot/backstage#166: Fix - Reduce Amount Of Info Logs
 - [ ] dojot/backstage#165: Fix - Delete Devices Mutation

dojot/gui-v2
------------

 - [ ] dojot/gui-v2#259: [DOJOT-203] - Fix selection of all items in device lists and templates list
 - [ ] dojot/gui-v2#257: Change action of delete template to use new mutation of BS
 - [ ] dojot/gui-v2#256: [DOJOT-162] - Fix name widget validation
 - [ ] dojot/gui-v2#258: [DOJOT-189] - Change text of error alert modal of delete template
 - [ ] dojot/gui-v2#255: [DOJOT-142] - Remove attribute color picker of Table Widget
 - [ ] dojot/gui-v2#254: Refactor/unique report file
 - [ ] dojot/gui-v2#252: [DOJOT-195] - Fix input style of tenantForm
 - [ ] dojot/gui-v2#253: [DOJOT-205] - Add translation key 'updated' to templates card orderBy input

dojot/dojot
-----------

 - [ ] dojot/dojot#2718: Feature - (Report Manager) Add Logger Configs
 - [ ] dojot/dojot#2728: [DOJOT-221] Fix: Optimize error handling in HTTP Error
 - [ ] dojot/dojot#2729: [DOJOT-149] Fix: CA delete request failed
 - [ ] dojot/dojot#2719: Fix - (Report Manager) Sonar Problems
 - [ ] dojot/dojot#2727: Fix - Report Manager Docs
 - [ ] dojot/dojot#2726: [DOJOT-149] [x509-identity-mgmt] Fix: topic in kafka producer

dojot/docker-compose
--------------------

 - [ ] dojot/docker-compose#342: Fix - Report Manager Logger Configs
 - [ ] dojot/docker-compose#345: [DOJOT-196] Add: resources and permissions in kong keycloak client for new service

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#237: Telegraf deployment and Postgres script
 - [ ] dojot/ansible-dojot#236: deploy report-manager, report-nx, config v2k keycloak secret, config audit volume in kong, config audit in kong, update keycloak/customRealmRepresentation.json

 

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/dev-alpha.4
----
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/dev-alpha.4
----
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/dev-alpha.4
----
