### ISSUE TITLE
Backlog for pre-release v1.0.0-rc.1

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2752]
### Backlog:

API Documentations:

https://dojot.github.io/device-manager/apiary_v1.0.0-rc.1.html
https://dojot.github.io/data-manager/apiary_v1.0.0-rc.1.html
https://dojot.github.io/cron/apiary_v1.0.0-rc.1.html
https://dojot.github.io/dojot/iam/x509-identity-mgmt/apiary_v1.0.0-rc.1.html
https://dojot.github.io/dojot/subscription-engine/kafka-ws/apiary_v1.0.0-rc.1.html
https://dojot.github.io/dojot/storage/time-series/influxdb/retriever/doc.html?version=v1.0.0-rc.1
https://dojot.github.io/dojot/storage/file/minio/file-mgmt/doc.html?version=v1.0.0-rc.1
https://dojot.github.io/dojot/data-visualization/reports/report-manager/doc.html?version=v1.0.0-rc.1

dojot/backstage
---------------
 - [ ] dojot/backstage#168: Added flow APIs
 - [ ] dojot/backstage#167: Adiciona registro de erro de GraphQL no log

dojot/gui-v2
------------
 - [ ] dojot/gui-v2#279: [DOJOT-204] - Add creation date and time in template grid mode
 - [ ] dojot/gui-v2#280: small tweak to color property
 - [ ] dojot/gui-v2#270: [DOJOT-137] - Improved favorite device listing
 - [ ] dojot/gui-v2#273: Add device id input to device creation wizard
 - [ ] dojot/gui-v2#274: fix for automatic color selection
 - [ ] dojot/gui-v2#275, linked issues #6015 #5995 #5990 #6015 #6015 #6015: Bump moment from 2.29.1 to 2.29.4 in /MFE/flow
 - [ ] dojot/gui-v2#269: Flow GUI
 - [ ] dojot/gui-v2#272: Menu Style Fix
 - [ ] dojot/gui-v2#268: Fix - package.json versions

dojot/cron
----------
 - [ ] dojot/cron#81: [DOJOT-202] Update: documentation

dojot/device-manager
--------------------
 - [ ] dojot/device-manager#208: [DOJOT-229] Fix - Format log timestamp correctly

dojot/flowbroker
----------------
 - [ ] dojot/flowbroker#424: test removed
 - [ ] dojot/flowbroker#423: "image route does not need authentication"

dojot/dojot
-----------
 - [ ] dojot/dojot#2750: [DOJOT-241] Fix - Report Manager Logger Prefix
 - [ ] dojot/dojot#2751: Fix - Report Manager Prisma
 - [ ] dojot/dojot#2749: [DOJOT- 214] Fix: in device-manager-natch env settings

dojot/docker-compose
--------------------
 - [ ] dojot/docker-compose#350: fix depends_on and healthcheck
 - [ ] dojot/docker-compose#349: Fix - Reports NX Profiles
 - [ ] dojot/docker-compose#348: Added Flow Broker services
 - [ ] dojot/docker-compose#347: Fix - Report Manager Log Level

dojot/ansible-dojot
-------------------
 - [ ] dojot/ansible-dojot#240: deploy flowbroker and fix report_manager
 - [ ] dojot/ansible-dojot#239: Deploy device manager batch
 - [ ] dojot/ansible-dojot#232: Telemetria

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v1.0.0-rc.1
----
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v1.0.0-rc.1
----
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v1.0.0-rc.1
----
