### ISSUE TITLE
Backlog for pre-release v1.0.0-rc.2

### ISSUE THREAD

**Issue by marianoleonardo** [dojot/dojot#2795]
### Backlog:

dojot/gui-v2
------------

 - [x] dojot/gui-v2#298: Add tooltip to menu icon button
 - [ ] dojot/gui-v2#299: add ace editor to template node
 - [ ] dojot/gui-v2#300: Fix letter colors in FLOW menu in DARK MODE theme
 - [ ] dojot/gui-v2#297: Fix wrong application background color changes
 - [x] dojot/gui-v2#290: [DOJOT-159] - Fix widget translation
 - [ ] dojot/gui-v2#288: Sort flow
 - [x] dojot/gui-v2#285: [DOJOT-243] - Disabled device: Inform the user about this feature
 - [x] dojot/gui-v2#281: [DOJOT-248] -  Refresh report list
 - [x] dojot/gui-v2#282: [DOJOT-234] - Change the term 'model' to 'template'
 - [ ] dojot/gui-v2#286: Remove codecov from github actions
 - [ ] dojot/gui-v2#283: Changed the initial load

dojot/flowbroker
----------------

 - [x] dojot/flowbroker#425: fix in multi actuation node

dojot/dojot
-----------

 - [ ] dojot/dojot#2767: Remove codecov from github actions
 - [x] dojot/dojot#2762: [DOJOT-247] - Fix problem deleting templates with associated devices

dojot/ansible-dojot
-------------------

 - [ ] dojot/ansible-dojot#249: Fix Dashboard Telemetria
 - [ ] dojot/ansible-dojot#248: Fix CustomRealm
 - [ ] dojot/ansible-dojot#245: Healthcheck to all services
 - [ ] dojot/ansible-dojot#242: Fixing monitoring

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v1.0.0-rc.2
----
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v1.0.0-rc.2
----
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v1.0.0-rc.2
----

[DOJOT-159]: https://dojot.atlassian.net/browse/DOJOT-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-243]: https://dojot.atlassian.net/browse/DOJOT-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-248]: https://dojot.atlassian.net/browse/DOJOT-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-234]: https://dojot.atlassian.net/browse/DOJOT-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-247]: https://dojot.atlassian.net/browse/DOJOT-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
