### ISSUE TITLE
Backlog for pre-release v1.0.0-rc.3

### ISSUE THREAD

**Issue by danielapetito** [dojot/dojot#2828]
### Backlog:

dojot/backstage
---------------
 - [ ] dojot/backstage#178: Fix/backstage db error
 - [ ] dojot/backstage#177: [dojot-288] Desacopla backstage do x509
 - [ ] dojot/backstage#175: remove db from databaseOptions in db/index.js
 - [ ] dojot/backstage#171: [DOJOT-242] - Configure environment variable with URL of each dojot service
 - [ ] dojot/backstage#173: Corrige nome da variável

dojot/gui-v2
------------
 - [ ] dojot/gui-v2#305: [DOJOT-231] - Add 'copy to clipboard' to device id column in device list
 - [ ] dojot/gui-v2#304: Changed map marker to get color dynamically
 - [ ] dojot/gui-v2#303: [DOJOT-280] - Add sorting on the certificate binding to a device screen
 - [ ] dojot/gui-v2#302: [DOJOT-281] - Change text on deletion of selected certificates
 - [ ] dojot/gui-v2#301: removed publish-ftp node

dojot/device-manager
--------------------
 - [x] dojot/device-manager#210: [v1.0.0] [DOJOT-200] Correção: invocando rollback quando há um erro na transação e resolvendo formatação do log de erro dessa operação.

dojot/dojot
-----------
 - [x] dojot/dojot#2826: Log improvement
 - [x] dojot/dojot#2811: [v1.0.0] [Dojot-278] Correção: Basic-auth response com erro em todos os cenários
 - [x] dojot/dojot#2809: [v1.0.0][DOJOT-286] Atualização do regex para a validação do nome de um tenant.
 - [x] dojot/dojot#2807: [v1.0.0] [DOJOT-225] Correção da documentação do device-manager-batch
 - [x] dojot/dojot#2805: [v1.0.0][Dojot-259] IoT-agent converte objeto JSON em texto.
 - [ ] dojot/dojot#2799: [v1.0.0] [DOJOT-187] Nova rota para consultar o cache de dispositivos no influxdb-retriever e alguns aprimor
 - [x] dojot/dojot#2804: [v1.0.0] [DOJOT-86] Melhoria na doc e na na legibilidade do código do basic-auth
 - [x] dojot/dojot#2801: [v1.0.0] [DOJOT-35] File-mgmt não é interropido quando há uma falha
 - [ ] dojot/dojot#2796: [v1.0.0][DOJOT-288] Novo conversor de dados para o influxdb-retriever

dojot/docker-compose
--------------------
 - [x] dojot/docker-compose#357: [v1.0.0][Dojot-278]  Removendo: Variaveis que podem causar erros.

dojot/ansible-dojot
-------------------
 - [x] dojot/ansible-dojot#253: desabilitando health check alguns serviços devido alto consumo CPU

----
Baseline specification available at https://github.com/dojot/baseline-builder/releases/tag/v1.0.0-rc.3
----
----
Ansible available at https://github.com/dojot/ansible-dojot/releases/tag/v1.0.0-rc.3
----
----
Docker-compose available at https://github.com/dojot/docker-compose/releases/tag/v1.0.0-rc.3
----

[DOJOT-242]: https://dojot.atlassian.net/browse/DOJOT-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-231]: https://dojot.atlassian.net/browse/DOJOT-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-280]: https://dojot.atlassian.net/browse/DOJOT-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-281]: https://dojot.atlassian.net/browse/DOJOT-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOJOT-200]: https://dojot.atlassian.net/browse/DOJOT-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
