### ISSUE TITLE
Publish image on docker hub is not working

### ISSUE THREAD

**Issue by eliasreis54** [dojot/dojot#794]
My PR was approved in device-manager repository and the image was not publish in docker hub. It happened because the username and password was incorrect. I think it need to be revised in all repositories.

Job: https://travis-ci.org/dojot/device-manager/builds/454029910#L1137

Services to be checked:

- [X] dojot/history: dojot/history#31, username and password updated on travis-ci.org
- [X] dojot/persister: dojot/history#31, username and password updated on travis-ci.org
- [x] dojot/iotagent-mosca: already OK (dojot/iotagent-mosca#29), username and password updated on travis-ci.org
- [X] dojot/gui: dojot/gui#331, username and password updated on travis-ci.org
- [X] dojot/data-broker: dojot/data-broker#36, username and password updated on travis-ci.org
- [X] dojot/device-manager: dojot/device-manager#103, username and password updated on travis-ci.org
- [X] dojot/auth: already OK (dojot/auth#59), username and password updated on travis-ci.org
- [X] dojot/kong: dojot/kong#12, username and password updated on travis-ci.org
- [X] dojot/flowbroker: dojot/flowbroker#92, username and password updated on travis-ci.org
- [X] dojot/flowbroker-context-manager: dojot/flowbroker#92, username and password updated on travis-ci.org
