### ISSUE TITLE
Change docker base images for dojot services

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#797]
In the last few weeks we got some base images that were updated with the same tag (for instance, node:8 was updated from Debian Jessie to Debian Stretch). This caused our images to be built incorrectly (a few of them were built using old images and those which were updated could not be built due to errors). There should be a throughout analysis of all images so that the correct image is used (or a more specific one, such as node:8.14.0-jessie or node:8.14.0-alpine for instance).

These are the images that needs to be tested:

- [X] dojot/history: dojot/history#30
- [X] dojot/persister: dojot/history#30
- [X] dojot/iotagent-mosca: dojot/iotagent-mosca#32
- [X] dojot/gui: dojot/gui#330
- [X] dojot/data-broker: dojot/data-broker#35
- [X] dojot/device-manager: dojot/device-manager#102
- [X] dojot/auth: dojot/auth#68
- [X] dojot/kong: already with specific image (kong:0.11)
- [X] dojot/flowbroker: dojot/flowbroker#91
- [X] dojot/flowbroker-context-manager: dojot/flowbroker#91

**Comment by danielnunesdeoliveira** [comment]
#328

**Comment by danielnunesdeoliveira** [comment]
Are you talking about this [Issue](https://github.com/dojot/gui/issues/328#issue-386843134) ?

**Comment by giovannicuriel** [comment]
Not actually, @danielnunesdeoliveira. I ask the GUI guys to check on your issue. It might be related to a few new things they are working on right now (if you used the code on `master` branch, this is definitely the case :sunglasses: )
