### ISSUE TITLE
Implement healthcheck

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#997]
Services that need healthchecking:
- [ ] dojot/history:
  - [ ] uptime
  - [ ] memory usage (system)
  - [ ] cpu usage (system)
  - [ ] connection with mongodb
- [ ] dojot/persister:
  - [ ] uptime
  - [ ] memory usage (system)
  - [ ] cpu usage (system)
  - [ ] connection with mongodb
  - [ ] connection with kafka
- [ ] dojot/iotagent-mosca: dojot/iotagent-mosca#48
  - [x] uptime
  - [x] memory usage (system)
  - [x] cpu usage (system)
  - [x] connection with redis
  - [x] connection with kafka
- [x] dojot/cron: dojot/cron#3
  - [x] uptime (developing, Giovanni)
  - [x] memory usage (system)
  - [x] cpu usage (system)
  - [x] connection with mongodb
  - [x] connection with kafka
- [x] dojot/data-broker: dojot/data-broker#50
  - [x] uptime
  - [x] memory usage (system)
  - [x] cpu usage (system)
  - [x] connection with kafka
  - [x] connection with redis
- [ ] dojot/device-manager
  - [ ] uptime
  - [ ] memory usage (system)
  - [ ] cpu usage (system)
  - [ ] connection with kafka
  - [ ] connection with redis
- [x] dojot/auth
  - [x] uptime
  - [ ] memory usage (system)
  - [ ] cpu usage (system)
  - [ ] connection with kong
  - [ ] connection with kafka
  - [ ] connection with redis
- [x] dojot/flowbroker: dojot/flowbroker#126
  - [x] uptime
  - [x] memory usage (system)
  - [x] cpu usage (system)
  - [x] connection with mongodb
  - [x] connection with kafka
- [ ] dojot/flowbroker-context-manager (?)
